export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  categories: string[]; // Array of category IDs from categories: Category[]
  keywords: string[];
  longTailKeywords?: string[]; // Long-tail search queries to capture (e.g. "how to convert base64 to jpg online")
  isNew?: boolean;
  searchVolume: number;
  label?: 'popular' | 'new' | 'coming-soon' | 'test' | ''; // Tool label for badges
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
  tools: Tool[];
}

// Tool data
export const tools: Tool[] = [
  // Data & Conversion Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description:
      'Format, validate and beautify JSON data with syntax highlighting',
    icon: '📋',
    route: '/tools/json-formatter',
    categories: ['data', 'formatters'],
    keywords: ['json', 'format', 'validate', 'prettify', 'parse'],
    searchVolume: 8500,
    label: '',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV files to JSON format with customizable options',
    icon: '🔄',
    route: '/tools/csv-to-json',
    categories: ['data'],
    keywords: [
      'csv',
      'json',
      'convert',
      'data',
      'transform',
      'spreadsheet',
      'excel',
    ],
    searchVolume: 7200,
    label: '',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description:
      'Convert JSON to CSV with advanced formatting, flattening, and column mapping options',
    icon: '📊',
    route: '/tools/json-to-csv',
    categories: ['data', 'dev'],
    keywords: [
      'json to csv',
      'json converter',
      'convert json to excel',
      'json to csv online',
      'json parser',
      'json',
      'csv',
      'excel',
      'spreadsheet',
      'export',
      'data transformation',
      'flatten json',
      'json array',
      'tabular data',
    ],
    searchVolume: 25000,
    label: '',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation',
    icon: '🗃️',
    route: '/tools/sql-formatter',
    categories: ['formatters', 'data', 'text'],
    keywords: ['sql', 'format', 'database', 'query', 'beautify'],
    searchVolume: 6800,
    label: '',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description:
      'Format, validate, and minify XML documents with syntax highlighting and XPath support',
    icon: '📄',
    route: '/tools/xml-formatter',
    categories: ['formatters', 'data'],
    keywords: [
      'xml',
      'formatter',
      'beautify',
      'minify',
      'validate',
      'parser',
      'xpath',
      'namespace',
      'schema',
      'soap',
      'rss',
      'svg',
      'markup',
      'xsd',
      'dtd',
    ],
    searchVolume: 8900,
    label: '',
  },
  {
    id: 'xml-to-json-converter',
    name: 'XML to JSON Converter',
    description:
      'Convert XML documents to JSON format with attribute handling, namespace support, and smart array detection',
    icon: '🔄',
    route: '/tools/xml-to-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'xml to json',
      'xml converter',
      'convert xml to json',
      'xml parser',
      'xml',
      'json',
      'converter',
      'parser',
      'namespace',
      'attributes',
      'cdata',
      'soap to json',
      'rss to json',
      'api',
      'data transformation',
    ],
    searchVolume: 12500,
    label: '',
  },

  // Encoding & Security Tools
  {
    id: 'base64-encode',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with file support',
    icon: '🔐',
    route: '/tools/base64-encode',
    categories: ['encoding', 'base64'],
    keywords: ['base64', 'encode', 'decode', 'encryption', 'security'],
    searchVolume: 9200,
    label: '',
  },
  {
    id: 'url-encode',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components and query parameters',
    icon: '🔗',
    route: '/tools/url-encode',
    categories: ['encoding'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    searchVolume: 7800,
    label: '',
  },
  {
    id: 'html-encode-decode',
    name: 'HTML Encoder/Decoder',
    description:
      'Convert text to HTML entities and decode HTML entities to plain text',
    icon: '🏷️',
    route: '/tools/html-encode-decode',
    categories: ['encoding', 'text'],
    keywords: [
      'html',
      'encode',
      'decode',
      'entities',
      'escape',
      'unescape',
      'sanitize',
      'xss',
      'special characters',
      'xml',
    ],
    isNew: true,
    searchVolume: 6200,
    label: '',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256 and other hash functions',
    icon: '#️⃣',
    route: '/tools/hash-generator',
    categories: ['encoding'],
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'checksum'],
    searchVolume: 6500,
    label: '',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and validate JSON Web Tokens (JWT)',
    icon: '🎫',
    route: '/tools/jwt-decoder',
    categories: ['encoding'],
    keywords: ['jwt', 'json', 'web', 'token', 'decode'],
    isNew: true,
    searchVolume: 5800,
    label: '',
  },
  {
    id: 'bcrypt-hash-generator',
    name: 'Bcrypt Hash Generator',
    description:
      'Generate and verify bcrypt password hashes with configurable cost factor for secure password storage',
    icon: '🔒',
    route: '/tools/bcrypt-hash-generator',
    categories: ['encoding', 'dev'],
    keywords: [
      'bcrypt',
      'hash',
      'password',
      'generator',
      'verify',
      'security',
      'encryption',
      'salt',
      'rounds',
      'cost factor',
    ],
    searchVolume: 10000,
    label: '',
  },
  {
    id: 'base64-to-pdf',
    name: 'Base64 to PDF',
    description: 'Convert Base64 encoded data to PDF files and download them',
    icon: '📄',
    route: '/tools/base64-to-pdf',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'pdf',
      'convert',
      'download',
      'decode',
      'file',
      'document',
      'viewer',
      'preview',
      'base64 to pdf',
      'base64 decode pdf',
      'base64 string',
      'pdf converter',
      'online',
      'free',
    ],
    searchVolume: 3200,
    label: '',
  },
  {
    id: 'base64-to-gif',
    name: 'Base64 to GIF',
    description:
      'Convert Base64 encoded data to GIF images and download them with preview',
    icon: '🎞️',
    route: '/tools/base64-to-gif',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'gif',
      'image',
      'convert',
      'download',
      'decode',
      'animation',
    ],
    longTailKeywords: [
      'base64 to gif converter online free',
      'convert base64 string to gif image',
      'decode base64 to gif file download',
      'base64 animated gif decoder online',
      'how to convert base64 to gif image',
      'base64 to gif decoder with instant preview',
      'save base64 as gif file no registration',
      'base64 data uri to gif converter',
      'online base64 to gif converter no upload',
      'convert base64 to animated gif free',
      'decode base64 gif from api response',
      'free base64 to gif decoder client side',
    ],
    searchVolume: 2800,
    label: '',
  },
  {
    id: 'base64-to-png',
    name: 'Base64 to PNG',
    description:
      'Convert Base64 encoded data to PNG images with instant preview and download',
    icon: '🖼️',
    route: '/tools/base64-to-png',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'png',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    longTailKeywords: [
      'base64 to png converter online free',
      'convert base64 string to png image',
      'decode base64 to png file download',
      'base64 png decoder with instant preview',
      'how to convert base64 to png image',
      'base64 to png transparent background preview',
      'save base64 as png file no registration',
      'base64 data uri to png converter',
      'online base64 to png converter no upload',
      'convert base64 to png with alpha channel',
      'decode base64 png from api response',
      'free base64 to png decoder client side',
    ],
    searchVolume: 3500,
    label: '',
  },
  {
    id: 'base64-to-jpg',
    name: 'Base64 to JPG',
    description:
      'Convert Base64 encoded data to JPG/JPEG images with instant preview and download',
    icon: '📸',
    route: '/tools/base64-to-jpg',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'jpg',
      'jpeg',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    longTailKeywords: [
      'base64 to jpg converter online free',
      'convert base64 string to jpeg image',
      'decode base64 to jpg file download',
      'base64 jpeg decoder with instant preview',
      'how to convert base64 to jpg image',
      'base64 to jpeg quality estimation preview',
      'save base64 as jpg file no registration',
      'base64 data uri to jpg converter',
      'online base64 to jpeg converter no upload',
      'decode base64 jpeg from api response',
      'free base64 to jpg no signup no upload',
      'free base64 to jpeg decoder client side',
    ],
    searchVolume: 4200,
    label: '',
  },
  {
    id: 'base64-to-webp',
    name: 'Base64 to WebP',
    description:
      'Convert Base64 encoded data to WebP images with instant preview, transparency support and compression info',
    icon: '⚡',
    route: '/tools/base64-to-webp',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'webp',
      'image',
      'convert',
      'download',
      'decode',
      'modern',
      'compression',
      'lossy',
      'lossless',
    ],
    longTailKeywords: [
      'base64 to webp converter online free',
      'convert base64 string to webp image',
      'decode base64 to webp file',
      'base64 webp decoder online',
      'how to convert base64 to webp',
      'base64 to webp with instant preview and download',
      'decode animated webp from base64 string',
      'base64 data uri to webp converter',
      'online base64 to webp converter no upload',
      'convert base64 to webp with transparency',
      'free base64 to webp converter no signup required',
      'browser based base64 to webp decoder tool',
    ],
    searchVolume: 3800,
    label: '',
  },
  {
    id: 'excel-filter',
    name: 'Excel Filter Tool',
    description:
      'Upload Excel files and apply dynamic filters to tables with search, sort, and export capabilities',
    icon: '📊',
    route: '/tools/excel-filter',
    categories: ['data'],
    keywords: [
      'excel',
      'filter',
      'spreadsheet',
      'table',
      'data',
      'search',
      'sort',
      'export',
      'csv',
      'xlsx',
      'query',
      'analyze',
      'viewer',
      'browser',
      'online',
    ],
    searchVolume: 8500,
    label: '',
  },

  // Text & Format Tools
  {
    id: 'instagram-font-generator',
    name: 'Instagram Font Generator',
    description:
      'Generate stylized Unicode fonts for Instagram, WhatsApp, and social media bios',
    icon: '✨',
    route: '/tools/instagram-font-generator',
    categories: ['social', 'text'],
    keywords: [
      'instagram',
      'font',
      'generator',
      'unicode',
      'text',
      'style',
      'fancy',
      'bio',
      'whatsapp',
      'social',
      'media',
      'bold',
      'italic',
      'cursive',
      'monospace',
      'aesthetic',
      'fonts for instagram',
      'instagram bio fonts',
      'fancy text generator',
      'unicode text',
      'stylish text',
      'cool fonts',
      'text decorator',
    ],
    searchVolume: 82000,
    label: '',
  },
  {
    id: 'linkedin-post-formatter',
    name: 'LinkedIn Post Formatter',
    description:
      'Format LinkedIn posts with bold, italic, and special characters using Unicode. Increase engagement with professional formatting.',
    icon: '💼',
    route: '/tools/linkedin-post-formatter',
    categories: ['social', 'text'],
    keywords: [
      'linkedin',
      'post',
      'formatter',
      'bold',
      'italic',
      'unicode',
      'text',
      'formatting',
      'social',
      'media',
      'professional',
      'engagement',
      'bullet',
      'points',
      'linkedin post',
      'linkedin formatting',
      'linkedin bold text',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description:
      'Compare files and code with advanced diff features and syntax highlighting',
    icon: '📝',
    route: '/tools/text-diff',
    categories: ['text', 'dev'],
    keywords: [
      'diff',
      'compare',
      'text',
      'difference',
      'merge',
      'patch',
      'git',
      'code',
      'file',
    ],
    searchVolume: 5200,
    label: '',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description:
      'Edit and preview Markdown with live rendering, export to HTML/PDF, and comprehensive statistics',
    icon: '📖',
    route: '/tools/markdown-preview',
    categories: ['text', 'formatters'],
    keywords: [
      'markdown',
      'preview',
      'html',
      'convert',
      'format',
      'editor',
      'gfm',
      'github',
      'export',
      'pdf',
    ],
    searchVolume: 4800,
    label: '',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with live matching',
    icon: '🔍',
    route: '/tools/regex-tester',
    categories: ['text'],
    keywords: ['regex', 'regexp', 'pattern', 'test', 'match'],
    searchVolume: 7500,
    label: '',
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID/GUID in various formats (v1, v4, etc.)',
    icon: '🆔',
    route: '/tools/uuid-generator',
    categories: ['generators'],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    searchVolume: 8200,
    label: '',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords with customizable options',
    icon: '🔑',
    route: '/tools/password-generator',
    categories: ['generators'],
    keywords: ['password', 'generate', 'secure', 'random', 'strong'],
    searchVolume: 9500,
    label: '',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description:
      'Generate QR codes with advanced customization, logos, batch processing and developer tools',
    icon: '📱',
    route: '/tools/qr-generator',
    categories: ['generators', 'dev', 'web'],
    keywords: [
      'qr',
      'code',
      'generate',
      'barcode',
      'scan',
      'wifi',
      'vcard',
      'batch',
      'svg',
      'logo',
      'api',
      'developer',
    ],
    searchVolume: 9800,
    label: '',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description:
      'Generate all types of barcodes - EAN, UPC, Code 128, QR codes, Data Matrix and more with customization',
    icon: '📊',
    route: '/tools/barcode-generator',
    categories: ['generators', 'dev'],
    keywords: [
      'barcode',
      'generator',
      'ean',
      'upc',
      'code 128',
      'code 39',
      'qr code',
      'data matrix',
      'isbn',
      'retail',
      'product',
      'inventory',
      'shipping',
      'warehouse',
      'label',
      'scanner',
      'batch',
      'svg',
      'png',
      'pdf',
    ],
    searchVolume: 8900,
    label: '',
  },

  // Web & Design Tools
  {
    id: 'color-picker',
    name: 'Color Picker',
    description:
      'Professional color picker with palettes, contrast checker and format conversion',
    icon: '🎨',
    route: '/tools/color-picker',
    categories: ['web', 'dev'],
    keywords: [
      'color',
      'picker',
      'hex',
      'rgb',
      'hsl',
      'hsv',
      'cmyk',
      'palette',
      'generator',
      'contrast',
      'checker',
      'wcag',
      'accessibility',
      'css',
      'tailwind',
      'material',
      'design',
      'eyedropper',
      'gradient',
      'harmony',
      'complementary',
      'triadic',
      'analogous',
      'color blindness',
      'lab',
      'pantone',
    ],
    searchVolume: 12500,
    label: '',
  },
  {
    id: 'color-format-converter',
    name: 'Color Format Converter',
    description:
      'Convert colors between HEX, RGB, HSL, HSV, and CMYK formats with palette generation and contrast checker',
    icon: '🌈',
    route: '/tools/color-format-converter',
    categories: ['web', 'generators', 'dev'],
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'hsl to hex',
      'hsv to rgb',
      'cmyk converter',
      'color format',
      'hex converter',
      'rgb converter',
      'color code',
      'color transformation',
      'color palette generator',
      'color shades',
      'color tints',
      'wcag contrast',
      'accessibility',
      'css colors',
      'color picker',
      'web colors',
      'design colors',
    ],
    searchVolume: 18500,
    label: '',
  },
  {
    id: 'image-optimizer',
    name: 'Image Optimizer',
    description: 'Compress and optimize images for web use',
    icon: '🖼️',
    route: '/tools/image-optimizer',
    categories: ['web'],
    keywords: ['image', 'optimize', 'compress', 'resize', 'webp'],
    isNew: true,
    searchVolume: 4500,
    label: 'coming-soon',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description:
      'Generate complete favicon packages with all sizes and formats',
    icon: '🖥️',
    route: '/tools/favicon-generator',
    categories: ['web', 'generators'],
    keywords: [
      'favicon',
      'icon',
      'apple-touch-icon',
      'android-chrome',
      'website-icon',
      'ico',
      'png',
      'image',
    ],
    isNew: true,
    searchVolume: 3200,
    label: '',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description:
      'Create beautiful CSS gradients with visual editor, presets and real-time preview',
    icon: '🌈',
    route: '/tools/gradient-generator',
    categories: ['web', 'generators'],
    keywords: [
      'gradient',
      'css',
      'linear',
      'radial',
      'conic',
      'color',
      'background',
      'design',
      'web',
      'ui',
      'tailwind',
      'svg',
      'maker',
      'tool',
      'generator',
    ],
    searchVolume: 15000,
    label: '',
  },

  // Dev Utilities
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description:
      'Advanced JSON validation with schema support, error reporting, and security checks',
    icon: '✅',
    route: '/tools/json-validator',
    categories: ['dev', 'data'],
    keywords: [
      'json',
      'validator',
      'schema',
      'validate',
      'check',
      'format',
      'jsonschema',
      'draft',
      'parser',
      'syntax',
      'error',
      'linter',
      'api',
      'development',
      'security',
      'audit',
      'compliance',
      'structure',
      'verification',
      'testing',
    ],
    searchVolume: 8400,
    label: '',
  },
  {
    id: 'crontab-builder',
    name: 'Crontab Expression Builder',
    description:
      'Parse, build, and validate cron expressions with visual builder, presets, and next execution times',
    icon: '⏰',
    route: '/tools/crontab-builder',
    categories: ['dev'],
    keywords: [
      'crontab',
      'cron',
      'scheduler',
      'unix',
      'linux',
      'automation',
      'parser',
      'builder',
      'expression',
    ],
    searchVolume: 5500,
    label: '',
  },
  {
    id: 'list-compare',
    name: 'List Compare & Diff Tool',
    description:
      'Advanced list comparison with set operations, fuzzy matching, and developer-friendly output formats',
    icon: '📋',
    route: '/tools/list-compare',
    categories: ['dev', 'text'],
    keywords: [
      'list compare',
      'diff lists',
      'set operations',
      'compare arrays',
      'list difference',
      'intersection',
      'union',
      'venn diagram',
      'array diff',
      'list merger',
      'duplicate finder',
      'fuzzy matching',
      'string comparison',
      'data analysis',
      'csv compare',
      'json compare',
      'package dependencies',
      'git files',
      'code compare',
    ],
    searchVolume: 18000,
    label: '',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description:
      'Convert cURL commands to production-ready code in any programming language with error handling and type safety',
    icon: '🔄',
    route: '/tools/curl-to-code',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to code',
      'curl converter',
      'curl to javascript',
      'curl to python',
      'http client generator',
      'api code generator',
      'curl to axios',
      'curl to fetch',
      'curl to golang',
      'curl to java',
      'curl to csharp',
      'curl to php',
      'curl to ruby',
      'rest api converter',
      'http request converter',
      'postman to code',
      'har to code',
      'api client generator',
      'sdk generator',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Converter',
    description:
      'Convert JSON to TypeScript interfaces with smart type inference, optional properties, and nested interface support',
    icon: '🔧',
    route: '/tools/json-to-typescript',
    categories: ['data', 'dev', 'generators'],
    keywords: [
      'json to typescript',
      'typescript interface generator',
      'json to interface',
      'type generator',
      'typescript types from json',
      'interface generator',
      'typescript converter',
      'json parser',
      'type inference',
      'typescript definitions',
      'api types',
      'type safety',
      'typescript interfaces',
      'json schema',
      'type generation',
      'developer tools',
      'code generator',
      'typescript typing',
      'json typing',
      'interface extractor',
    ],
    searchVolume: 35000,
    label: '',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier/Beautifier',
    description:
      'Minify, beautify and optimize CSS code with advanced compression options for production-ready stylesheets',
    icon: '🎨',
    route: '/tools/css-minifier',
    categories: ['formatters', 'dev', 'web'],
    keywords: [
      'css minifier',
      'css beautifier',
      'css formatter',
      'css compressor',
      'minimize css',
      'css optimization',
      'reduce css size',
      'css prettify',
      'css minify',
      'compress css',
      'css optimizer',
      'css cleaner',
      'production css',
      'css tools',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier/Beautifier',
    description:
      'Minify, beautify and optimize JavaScript code with ES6+ support, source maps, and advanced compression',
    icon: '⚡',
    route: '/tools/js-minifier',
    categories: ['formatters', 'dev'],
    keywords: [
      'javascript minifier',
      'js minifier',
      'javascript beautifier',
      'js formatter',
      'compress javascript',
      'minify js',
      'javascript optimizer',
      'js compression',
      'uglify js',
      'terser',
      'webpack optimizer',
      'production js',
      'bundle size',
      'tree shaking',
      'dead code elimination',
      'source maps',
      'obfuscation',
      'es6 minifier',
      'modern javascript',
    ],
    searchVolume: 22000,
    label: '',
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML to JSON Converter',
    description:
      'Convert between YAML and JSON formats with validation, type handling, and advanced formatting',
    icon: '🔄',
    route: '/tools/yaml-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'yaml',
      'json',
      'converter',
      'parser',
      'formatter',
      'yaml to json',
      'json to yaml',
      'data transformation',
      'config converter',
      'kubernetes',
      'docker',
      'docker compose',
      'ci cd',
      'github actions',
      'ansible',
      'swagger',
      'openapi',
      'multi document',
      'anchors',
      'aliases',
    ],
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    description:
      'Validate YAML syntax with detailed error messages, line numbers, and support for YAML 1.1 and 1.2 specifications',
    icon: '✅',
    route: '/tools/yaml-validator',
    categories: ['data', 'dev'],
    keywords: [
      'yaml',
      'validator',
      'syntax',
      'checker',
      'linter',
      'yaml lint',
      'yaml check',
      'yaml syntax',
      'validate yaml',
      'yaml error',
      'kubernetes',
      'docker compose',
      'config validation',
      'yaml 1.1',
      'yaml 1.2',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description:
      'Convert between Unix timestamps and human-readable dates with timezone support and batch processing',
    icon: '⏰',
    route: '/tools/unix-timestamp-converter',
    categories: ['data', 'dev'],
    keywords: [
      'unix',
      'timestamp',
      'epoch',
      'converter',
      'date',
      'time',
      'timezone',
      'utc',
      'milliseconds',
      'batch',
      'convert',
      'unix time',
      'epoch time',
      'datetime',
      'iso',
      'rfc',
      'posix',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'eml-to-html',
    name: 'EML to HTML Converter',
    description:
      'Convert EML email files to HTML with header extraction, attachment handling, and multi-view rendering',
    icon: '📧',
    route: '/tools/eml-to-html',
    categories: ['data', 'dev', 'formatters'],
    keywords: [
      'eml',
      'email',
      'html',
      'converter',
      'mime',
      'rfc822',
      'email parser',
      'eml viewer',
      'email to html',
      'email converter',
      'mime parser',
      'email headers',
      'email attachments',
      'email migration',
      'email forensics',
      'email template',
      'mailbox',
      'outlook',
      'thunderbird',
      'message',
      'rfc2822',
      'multipart',
      'base64',
      'quoted-printable',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'ai-prompt-token-counter',
    name: 'AI Prompt Token Counter',
    description:
      'Count tokens for AI prompts across GPT-4, Claude, Llama models with cost estimation and optimization',
    icon: '🤖',
    route: '/tools/ai-prompt-token-counter',
    categories: ['dev', 'generators', 'text'],
    keywords: [
      'token counter',
      'gpt token calculator',
      'claude tokens',
      'prompt tokens',
      'ai cost calculator',
      'token estimator',
      'openai tokens',
      'gpt-4 tokens',
      'llama tokens',
      'token count',
      'tokenizer',
      'api cost',
      'prompt optimization',
      'context window',
      'tiktoken',
      'ai pricing',
      'token visualization',
      'batch token count',
      'prompt engineering',
    ],
    searchVolume: 35000,
    label: '',
  },

  // PDF Tools
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description:
      'Convert PDF files to editable Word (DOCX) format with preserved formatting',
    icon: '📄',
    route: '/tools/pdf-to-word',
    categories: ['pdf'],
    keywords: [
      'pdf',
      'word',
      'docx',
      'convert',
      'converter',
      'pdf to word',
      'pdf to docx',
      'document',
      'edit',
      'format',
      'export',
      'transformation',
      'office',
      'microsoft word',
      'libre office',
      'editable',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description:
      'Convert multiple images (JPG, PNG, GIF, WebP) into a single PDF document with custom page sizes',
    icon: '🖼️',
    route: '/tools/image-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'image',
      'pdf',
      'convert',
      'jpg',
      'png',
      'gif',
      'webp',
      'image to pdf',
      'jpg to pdf',
      'png to pdf',
      'photo to pdf',
      'picture to pdf',
      'combine images',
      'merge images',
      'multiple images',
      'batch convert',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description:
      'Convert JPG and JPEG images to PDF format with custom page sizes and layout options',
    icon: '🖼️',
    route: '/tools/jpg-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'jpg',
      'jpeg',
      'pdf',
      'convert',
      'jpg to pdf',
      'jpeg to pdf',
      'image to pdf',
      'photo to pdf',
      'picture to pdf',
      'jpg converter',
      'jpeg converter',
      'batch convert',
      'multiple jpg',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'convert jpg to pdf online free',
      'jpg to pdf converter without losing quality',
      'combine multiple jpg images into one pdf',
      'jpg to pdf converter no watermark free',
      'how to convert jpeg to pdf without software',
      'free online jpg to pdf no download required',
      'batch convert jpg to pdf online free',
      'jpg to pdf with custom page size options',
      'convert jpeg photos to pdf document free',
      'jpg to pdf no signup no registration needed',
      'merge jpg files into single pdf online',
      'secure browser based jpg to pdf converter',
    ],
    searchVolume: 150000,
    label: '',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description:
      'Convert PNG images to PDF format with transparency support and custom page options',
    icon: '🖼️',
    route: '/tools/png-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'png',
      'pdf',
      'convert',
      'png to pdf',
      'image to pdf',
      'transparent',
      'transparency',
      'photo to pdf',
      'picture to pdf',
      'png converter',
      'batch convert',
      'multiple png',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'convert png to pdf online free',
      'png to pdf converter without losing quality',
      'combine multiple png images into one pdf',
      'png to pdf converter no watermark free',
      'how to convert png to pdf with transparency',
      'free online png to pdf no download required',
      'batch convert png to pdf online free',
      'png to pdf preserve transparent background',
      'merge png files into single pdf document',
      'png to pdf no signup no registration needed',
      'convert png screenshots to pdf document free',
      'secure browser based png to pdf converter',
    ],
    searchVolume: 100000,
    label: '',
  },
  {
    id: 'gif-to-pdf',
    name: 'GIF to PDF',
    description:
      'Convert GIF images to PDF format preserving quality with custom page sizes',
    icon: '🖼️',
    route: '/tools/gif-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'gif',
      'pdf',
      'convert',
      'gif to pdf',
      'image to pdf',
      'animated gif',
      'photo to pdf',
      'picture to pdf',
      'gif converter',
      'batch convert',
      'multiple gif',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 20000,
    label: '',
  },

  // Social Media Tools
  {
    id: 'whatsapp-link-generator',
    name: 'WhatsApp Link Generator',
    description:
      'Create WhatsApp click-to-chat links with pre-filled messages and QR codes',
    icon: '💬',
    route: '/tools/whatsapp-link-generator',
    categories: ['social', 'generators'],
    keywords: [
      'whatsapp',
      'link generator',
      'wa.me',
      'click to chat',
      'whatsapp link',
      'whatsapp api',
      'chat link',
      'whatsapp qr code',
      'business whatsapp',
      'whatsapp message',
      'wa link',
      'whatsapp shortcut',
      'contact link',
      'phone link',
      'messaging',
      'social media',
    ],
    searchVolume: 75000,
    longTailKeywords: [
      'whatsapp link generator online free',
      'create whatsapp click to chat link',
      'how to create wa.me link with message',
      'free whatsapp qr code generator with message',
      'whatsapp chat link generator with pre-filled message',
      'whatsapp link generator no registration required',
      'create whatsapp button for website free',
      'whatsapp direct message link without saving number',
      'whatsapp link for business card qr code',
      'how to make whatsapp link for website',
      'whatsapp short link generator for social media',
      'free whatsapp link creator with qr code',
    ],
    label: '',
  },
  {
    id: 'utm-builder',
    name: 'UTM Link Builder',
    description:
      'Create trackable URLs with UTM parameters for marketing campaigns, analytics, and link tracking',
    icon: '🔗',
    route: '/tools/utm-builder',
    categories: ['social', 'generators', 'web'],
    keywords: [
      'utm',
      'link builder',
      'url builder',
      'utm parameters',
      'campaign tracking',
      'utm generator',
      'google analytics',
      'utm tags',
      'marketing links',
      'utm source',
      'utm medium',
      'utm campaign',
      'link tracking',
      'campaign url',
      'url tracking',
      'analytics',
      'marketing',
      'social media tracking',
      'qr code',
      'short link',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'youtube-timestamp-generator',
    name: 'YouTube Timestamp Generator',
    description:
      'Create YouTube timestamps and chapters with automatic link generation and time conversion',
    icon: '⏱️',
    route: '/tools/youtube-timestamp-generator',
    categories: ['social', 'generators'],
    keywords: [
      'youtube',
      'timestamp',
      'chapters',
      'youtube chapters',
      'video timestamp',
      'timestamp generator',
      'youtube time',
      'video chapters',
      'youtube link',
      'time converter',
      'hh:mm:ss',
      'video navigation',
      'youtube creator',
      'video description',
      'timestamp link',
    ],
    searchVolume: 35000,
    label: '',
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description:
      'Calculate Unix file permissions with visual grid, octal and symbolic notation converter',
    icon: '🔒',
    route: '/tools/chmod-calculator',
    categories: ['dev', 'generators'],
    keywords: [
      'chmod',
      'permissions',
      'linux',
      'unix',
      'file permissions',
      'chmod calculator',
      'chmod converter',
      'octal permissions',
      'symbolic permissions',
      'rwx',
      'read write execute',
      'owner group others',
      'chmod 755',
      'chmod 644',
      'chmod 777',
      'permission bits',
      'sysadmin',
      'server',
      'shell',
      'terminal',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'htaccess-generator',
    name: 'Htaccess Generator',
    description:
      'Generate .htaccess files for Apache with redirects, security rules, caching, and URL rewriting',
    icon: '⚙️',
    route: '/tools/htaccess-generator',
    categories: ['dev', 'generators', 'web'],
    keywords: [
      'htaccess',
      'htaccess generator',
      'apache',
      'redirect',
      '301 redirect',
      '302 redirect',
      'url rewrite',
      'mod_rewrite',
      'security headers',
      'caching',
      'gzip compression',
      'force https',
      'www redirect',
      'custom error pages',
      'directory protection',
      'password protect',
      'hotlink protection',
      'ip blocking',
      'file access',
      'mime types',
      'server configuration',
      'web server',
      'seo redirect',
    ],
    searchVolume: 18000,
    label: '',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description:
      'Generate placeholder text for designs, mockups, and layouts with customizable word, sentence, or paragraph count',
    icon: '📝',
    route: '/tools/lorem-ipsum-generator',
    categories: ['text', 'generators'],
    keywords: [
      'lorem ipsum',
      'lorem ipsum generator',
      'placeholder text',
      'dummy text',
      'filler text',
      'sample text',
      'text generator',
      'lipsum',
      'blind text',
      'greeking',
      'mockup text',
      'design placeholder',
      'paragraph generator',
      'random text',
      'latin text',
    ],
    longTailKeywords: [
      'lorem ipsum generator online free',
      'generate lorem ipsum paragraphs',
      'lorem ipsum copy paste',
      'placeholder text generator for designers',
      'dummy text generator for website mockup',
      'how to generate lorem ipsum text',
      'lorem ipsum generator with word count',
      'custom lorem ipsum paragraph generator',
      'free online placeholder text generator',
      'lorem ipsum sentences generator no signup',
      'generate dummy text for web design',
      'lipsum generator with custom length',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'string-case-converter',
    name: 'String Case Converter',
    description:
      'Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and more',
    icon: '🔤',
    route: '/tools/string-case-converter',
    categories: ['text', 'dev'],
    keywords: [
      'string case converter',
      'case converter',
      'camelCase',
      'PascalCase',
      'snake_case',
      'kebab-case',
      'CONSTANT_CASE',
      'SCREAMING_SNAKE_CASE',
      'Title Case',
      'Sentence case',
      'lowercase',
      'uppercase',
      'text transform',
      'variable naming',
      'code formatting',
      'naming convention',
      'string transformation',
      'text case',
      'convert case',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'binary-to-text',
    name: 'Binary to Text Converter',
    description:
      'Convert binary numbers to text and vice versa with support for ASCII, UTF-8, and hex formats',
    icon: '🔢',
    route: '/tools/binary-to-text',
    categories: ['encoding', 'data'],
    keywords: [
      'binary to text',
      'text to binary',
      'binary converter',
      'binary decoder',
      'binary encoder',
      'ascii binary',
      'binary string',
      'binary code',
      'binary translation',
      '01 to text',
      'binary ascii converter',
      'binary to ascii',
      'ascii to binary',
      'hex to binary',
      'binary to hex',
      'utf-8 binary',
    ],
    searchVolume: 6500,
    label: '',
  },
  {
    id: 'js-object-to-json',
    name: 'JavaScript Object to JSON',
    description:
      'Convert JavaScript objects to valid JSON with circular reference detection, function handling, and BigInt support',
    icon: '🔄',
    route: '/tools/js-object-to-json',
    categories: ['data', 'dev'],
    keywords: [
      'javascript to json',
      'js object to json',
      'object to json',
      'json converter',
      'javascript object converter',
      'js to json online',
      'convert js to json',
      'json stringify',
      'object serialization',
      'circular reference',
      'bigint json',
      'function to json',
      'undefined json',
      'javascript parser',
      'json generator',
    ],
    searchVolume: 8500,
    label: '',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description:
      'Convert HTML to Markdown or Markdown to HTML with GFM table and code block support',
    icon: '🔄',
    route: '/tools/html-to-markdown',
    categories: ['text', 'formatters'],
    keywords: [
      'html to markdown',
      'markdown to html',
      'html to md',
      'html converter',
      'markdown converter',
      'html',
      'markdown',
      'convert',
      'md',
      'gfm',
      'github',
      'turndown',
      'wordpress to markdown',
      'notion markdown',
      'obsidian markdown',
      'copy html as markdown',
      'table',
      'code',
    ],
    searchVolume: 9000,
    label: '',
  },
];

// Group tools by category
export const categories: Category[] = [
  {
    id: 'data',
    name: 'Data & Conversion',
    description:
      'Transform and format data between different formats like JSON, CSV, XML, and SQL.',
    icon: '📊',
    tools: getToolsByCategory('data'),
  },
  {
    id: 'encoding',
    name: 'Encoding & Security',
    description:
      'Encode, decode, hash, and secure your data with various encryption methods.',
    icon: '🔐',
    tools: getToolsByCategory('encoding'),
  },
  {
    id: 'base64',
    name: 'Base64',
    description:
      'Convert Base64 encoded data to PDF, images, and other file formats with instant download and preview.',
    icon: '🔤',
    tools: getToolsByCategory('base64'),
  },
  {
    id: 'text',
    name: 'Text & Format',
    description:
      'Process, compare, and format text content with powerful text manipulation tools.',
    icon: '📝',
    tools: getToolsByCategory('text'),
  },
  {
    id: 'generators',
    name: 'Generators',
    description:
      'Generate UUIDs, passwords, QR codes, and other useful content for development.',
    icon: '⚡',
    tools: getToolsByCategory('generators'),
  },
  {
    id: 'web',
    name: 'Web & Design',
    description:
      'Tools for web developers and designers including color pickers and image optimization.',
    icon: '🎨',
    tools: getToolsByCategory('web'),
  },
  {
    id: 'dev',
    name: 'Dev Utilities',
    description:
      'Development utilities for testing APIs, validating schemas, and debugging code.',
    icon: '🔧',
    tools: getToolsByCategory('dev'),
  },
  {
    id: 'formatters',
    name: 'Formatters',
    description:
      'Format and beautify code, SQL, JSON, XML and other structured data.',
    icon: '🪄',
    tools: getToolsByCategory('formatters'),
  },
  {
    id: 'social',
    name: 'Social Media',
    description:
      'Tools for social media content creation, including Instagram, WhatsApp, Twitter, and Facebook.',
    icon: '📱',
    tools: getToolsByCategory('social'),
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description:
      'Professional PDF tools for conversion, editing, merging, splitting and optimization.',
    icon: '📄',
    tools: getToolsByCategory('pdf'),
  },
];

// Helper functions
export function getPopularTools(): Tool[] {
  return tools
    .sort((a, b) => b.searchVolume - a.searchVolume)
    .map((tool) => ({
      ...tool,
      keywords: tool.keywords || [], // Ensure keywords is always an array
    }));
}

export function searchTools(query: string): Tool[] {
  const searchTerm = query.toLowerCase();
  return tools
    .filter(
      (tool) =>
        tool.label !== 'coming-soon' &&
        (tool.name.toLowerCase().includes(searchTerm) ||
          tool.description.toLowerCase().includes(searchTerm) ||
          tool.keywords.some((keyword) =>
            keyword.toLowerCase().includes(searchTerm)
          ))
    )
    .sort((a, b) => b.searchVolume - a.searchVolume);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools
    .filter((tool) => {
      return tool.categories.includes(categoryId);
    })
    .sort((a, b) => {
      // First sort by searchVolume (descending), then by name (ascending) for deterministic order
      if (b.searchVolume !== a.searchVolume) {
        return b.searchVolume - a.searchVolume;
      }
      return a.name.localeCompare(b.name);
    });
}

// O(1) lookup map for tools by ID
export const toolsMap = new Map<string, Tool>(tools.map((t) => [t.id, t]));

export function getToolById(id: string): Tool | undefined {
  return toolsMap.get(id);
}

export function getCategoryColorClass(categoryColor: string): string {
  const colorClasses = {
    data: 'border-blue-500 bg-blue-50 dark:bg-blue-950',
    encoding: 'border-green-500 bg-green-50 dark:bg-green-950',
    text: 'border-purple-500 bg-purple-50 dark:bg-purple-950',
    generators: 'border-orange-500 bg-orange-50 dark:bg-orange-950',
    web: 'border-pink-500 bg-pink-50 dark:bg-pink-950',
    dev: 'border-yellow-500 bg-yellow-50 dark:bg-yellow-950',
    formatters: 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950',
    social: 'border-rose-500 bg-rose-50 dark:bg-rose-950',
    pdf: 'border-red-500 bg-red-50 dark:bg-red-950',
  };
  return (
    colorClasses[categoryColor as keyof typeof colorClasses] ||
    'border-blue-500 bg-blue-50 dark:bg-blue-950'
  );
}

export function getCategoryByTool(tool: Tool): Category | undefined {
  return categories.find((category) =>
    category.tools.some((t) => t.id === tool.id)
  );
}

export function getAllTools(): Tool[] {
  return tools;
}
