export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  categories: string[]; // Array of category IDs from categories: Category[]
  keywords: string[];
  longTailKeywords?: string[]; // Long-tail search queries to capture (e.g. "how to convert base64 to jpg online")
  isNew?: boolean;
  searchVolume: number;
  label?: 'popular' | 'new' | 'coming-soon' | 'test' | ''; // Tool label for badges
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
  tools: Tool[];
}

// Tool data
export const tools: Tool[] = [
  // Data & Conversion Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description:
      'Format, validate and beautify JSON data with syntax highlighting',
    icon: '📋',
    route: '/tools/json-formatter',
    categories: ['data', 'formatters'],
    keywords: ['json', 'format', 'validate', 'prettify', 'parse'],
    longTailKeywords: [
      'json formatter online free no signup',
      'format json online free no registration required',
      'json beautifier online free instant',
      'pretty print json online free no download',
      'how to format minified json online',
      'how to validate json syntax online free',
      'how to beautify json for readability online',
      'json formatter with syntax highlighting free',
      'json formatter with key sorting options online',
      'json validator and formatter for api responses',
      'best free json formatter and validator online',
      'format json without installing code editor',
    ],
    searchVolume: 400000,
    label: '',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV files to JSON format with customizable options',
    icon: '🔄',
    route: '/tools/csv-to-json',
    categories: ['data'],
    keywords: [
      'csv',
      'json',
      'convert',
      'data',
      'transform',
      'spreadsheet',
      'excel',
    ],
    longTailKeywords: [
      'csv to json converter online free no signup',
      'convert csv to json online free no registration',
      'csv to json converter free no download required',
      'convert csv file to json array online free',
      'how to convert csv to json online',
      'how to convert spreadsheet data to json format',
      'how to import csv data into json for api',
      'csv to json converter with custom delimiter support',
      'csv to json with automatic header detection free',
      'convert excel csv export to json for database',
      'best free csv to json converter online tool',
      'csv to json without installing python or node.js',
    ],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description:
      'Convert JSON to CSV with advanced formatting, flattening, and column mapping options',
    icon: '📊',
    route: '/tools/json-to-csv',
    categories: ['data', 'dev'],
    keywords: [
      'json to csv',
      'json converter',
      'convert json to excel',
      'json to csv online',
      'json parser',
      'json',
      'csv',
      'excel',
      'spreadsheet',
      'export',
      'data transformation',
      'flatten json',
      'json array',
      'tabular data',
    ],
    longTailKeywords: [
      'json to csv converter online free',
      'convert json to csv for excel online free',
      'json to csv converter no signup required',
      'convert json to csv for google sheets',
      'how to convert json to csv online',
      'how to convert nested json to csv',
      'how to flatten json for csv export',
      'json to csv converter with custom delimiter',
      'json to csv converter for api responses',
      'flatten nested json to csv online free',
      'best free json to csv converter online',
      'json to csv converter without file upload',
    ],
    searchVolume: 32000,
    label: '',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation',
    icon: '🗃️',
    route: '/tools/sql-formatter',
    categories: ['formatters', 'data', 'text'],
    keywords: ['sql', 'format', 'database', 'query', 'beautify'],
    longTailKeywords: [
      'sql formatter online free no signup',
      'format sql query online free no registration',
      'sql beautifier online free instant results',
      'beautify sql query online free no download',
      'how to format sql query for readability online',
      'how to beautify minified sql query online free',
      'how to indent sql statement online free',
      'sql formatter for mysql postgresql sqlite online',
      'sql formatter with syntax highlighting free online',
      'sql query formatter for code review and documentation',
      'best free sql formatter online for all dialects',
      'format sql without installing database client software',
    ],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description:
      'Format, validate, and minify XML documents with syntax highlighting and XPath support',
    icon: '📄',
    route: '/tools/xml-formatter',
    categories: ['formatters', 'data'],
    keywords: [
      'xml',
      'formatter',
      'beautify',
      'minify',
      'validate',
      'parser',
      'xpath',
      'namespace',
      'schema',
      'soap',
      'rss',
      'svg',
      'markup',
      'xsd',
      'dtd',
    ],
    longTailKeywords: [
      'xml formatter online free no signup',
      'format and beautify xml online free no registration',
      'xml formatter and validator free instant online',
      'minify xml file online free no upload',
      'how to format xml online for readability',
      'how to validate xml syntax online free',
      'how to beautify minified xml online',
      'xml formatter with xpath search support',
      'xml beautifier with namespace and schema support',
      'xml formatter for soap and rss feeds online',
      'best free xml formatter and validator online',
      'xml formatter without installing xml editor software',
    ],
    searchVolume: 40000,
    label: '',
  },
  {
    id: 'xml-to-json-converter',
    name: 'XML to JSON Converter',
    description:
      'Convert XML documents to JSON format with attribute handling, namespace support, and smart array detection',
    icon: '🔄',
    route: '/tools/xml-to-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'xml to json',
      'xml converter',
      'convert xml to json',
      'xml parser',
      'xml',
      'json',
      'converter',
      'parser',
      'namespace',
      'attributes',
      'cdata',
      'soap to json',
      'rss to json',
      'api',
      'data transformation',
    ],
    longTailKeywords: [
      'xml to json converter online free',
      'convert xml to json no signup required',
      'xml to json online converter free no download',
      'how to convert xml to json online',
      'convert soap xml response to json online free',
      'how to parse xml and convert to json format',
      'how to convert rss feed xml to json data',
      'xml to json converter with namespace support',
      'xml to json converter with smart array detection',
      'convert xml to json for api integration free',
      'best free xml to json converter online tool',
      'xml to json converter without installing software',
    ],
    searchVolume: 12000,
    label: '',
  },

  // Encoding & Security Tools
  {
    id: 'base64-encode',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with file support',
    icon: '🔐',
    route: '/tools/base64-encode',
    categories: ['encoding', 'base64'],
    keywords: ['base64', 'encode', 'decode', 'encryption', 'security'],
    longTailKeywords: [
      'base64 encoder decoder online free no signup',
      'encode text to base64 online free no registration',
      'decode base64 string to text online free',
      'base64 encoder for files and images online free',
      'how to encode text to base64 online',
      'how to decode base64 string to readable text',
      'how to convert image to base64 for html css',
      'base64 encoder with file upload support free',
      'base64 decoder with utf-8 and binary support',
      'base64 encode decode for api development free',
      'best free base64 encoder decoder online tool',
      'base64 converter without installing software',
    ],
    searchVolume: 150000,
    label: '',
  },
  {
    id: 'url-encode',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components and query parameters',
    icon: '🔗',
    route: '/tools/url-encode',
    categories: ['encoding'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    longTailKeywords: [
      'url encoder decoder online free no signup',
      'encode url online free no registration required',
      'decode percent encoded url online free',
      'url encode special characters online free tool',
      'how to url encode a string online',
      'how to decode url encoded string online free',
      'how to encode query parameters for api calls',
      'url encoder with full vs component encoding options',
      'decode encoded url parameters online free tool',
      'url encoder decoder for api and web development',
      'best free url encoder decoder online tool',
      'url encode decode without installing software',
    ],
    searchVolume: 50000,
    label: '',
  },
  {
    id: 'html-encode-decode',
    name: 'HTML Encoder/Decoder',
    description:
      'Convert text to HTML entities and decode HTML entities to plain text',
    icon: '🏷️',
    route: '/tools/html-encode-decode',
    categories: ['encoding', 'text'],
    keywords: [
      'html',
      'encode',
      'decode',
      'entities',
      'escape',
      'unescape',
      'sanitize',
      'xss',
      'special characters',
      'xml',
    ],
    longTailKeywords: [
      'html encode decode online free no signup',
      'encode html entities online free no registration',
      'decode html entities to plain text online free',
      'html entity encoder free instant online tool',
      'how to encode html special characters online',
      'how to decode html entities to readable text',
      'how to escape html for xss prevention online',
      'html encoder with named and decimal entities free',
      'html entity decoder with auto-detection online',
      'encode html for safe display in web pages free',
      'best free html encoder decoder online tool',
      'html encode decode without installing developer tools',
    ],
    isNew: true,
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-256, SHA-512 hashes and HMAC signatures — with file hashing, bulk mode, and hash comparison',
    icon: '#️⃣',
    route: '/tools/hash-generator',
    categories: ['encoding'],
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'hmac', 'checksum', 'file hash', 'hash compare', 'crc32'],
    longTailKeywords: [
      'hash generator online free no signup',
      'generate md5 sha256 hash online free no registration',
      'sha256 hash generator free instant online',
      'md5 hash generator online free no account',
      'how to generate md5 hash for file verification',
      'how to compute sha256 hash online for free',
      'how to verify file integrity using hash online',
      'hash generator for text and files online free',
      'sha512 hash generator with clipboard copy free',
      'cryptographic hash generator for security auditing',
      'best free hash generator online md5 sha256 sha512',
      'generate checksum without installing hashing tools',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Encoder/Decoder',
    description: 'Decode, verify, encode and sign JSON Web Tokens — all in your browser',
    icon: '🎫',
    route: '/tools/jwt-decoder',
    categories: ['encoding'],
    keywords: ['jwt', 'json', 'web', 'token', 'decode', 'encode', 'sign', 'verify', 'create', 'generator', 'signer', 'encoder', 'signature', 'expiration', 'validate', 'hs256', 'rs256', 'es256'],
    longTailKeywords: [
      'jwt decoder online free no signup',
      'decode jwt token online free no registration',
      'inspect jwt claims online free instant',
      'jwt decoder and validator online free tool',
      'how to decode jwt token online',
      'how to inspect jwt payload claims online free',
      'how to verify jwt expiration time online',
      'jwt decoder with claims analysis and validation',
      'jwt token inspector for debugging authentication',
      'decode json web token for api debugging free',
      'best free jwt decoder online security tool',
      'decode jwt without installing jwt library locally',
      'verify jwt signature online free',
      'jwt signature verifier online tool',
      'jwt token expiration checker online',
      'verify jwt hs256 signature online',
      'verify jwt rs256 public key online free',
      'jwt verifier in browser no server upload',
      'check jwt token validity and signature online',
      'jwt expiry countdown online tool',
      'jwt encoder online free no signup',
      'create jwt token online free no registration',
      'sign jwt online free instant',
      'jwt generator online free hs256 rs256',
      'how to create a jwt token online',
      'how to sign jwt online free no server',
      'jwt signer with hmac secret and rsa private key',
      'jwt encoder and decoder in the same tool',
      'generate signed jwt for testing api authentication',
      'jwt maker online free for developers',
      'jwt encoder with custom claims and expiration',
      'sign jwt hs256 with secret online browser based',
      'sign jwt rs256 with pem private key online',
      'sign jwt es256 ecdsa in browser no upload',
      'jwt builder online free test environment',
    ],
    isNew: true,
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'bcrypt-hash-generator',
    name: 'Bcrypt Hash Generator',
    description:
      'Generate and verify bcrypt password hashes with configurable cost factor for secure password storage',
    icon: '🔒',
    route: '/tools/bcrypt-hash-generator',
    categories: ['encoding', 'dev'],
    keywords: [
      'bcrypt',
      'hash',
      'password',
      'generator',
      'verify',
      'security',
      'encryption',
      'salt',
      'rounds',
      'cost factor',
    ],
    longTailKeywords: [
      'bcrypt hash generator online free no signup',
      'generate bcrypt password hash online free',
      'bcrypt hash generator no registration required',
      'bcrypt password hashing tool for developers free',
      'how to generate bcrypt hash for password storage',
      'how to verify bcrypt password hash online',
      'how to choose bcrypt cost factor rounds',
      'bcrypt hash generator with configurable rounds',
      'bcrypt password hash verifier online free',
      'bcrypt hash generator for node js php python',
      'best free bcrypt hash generator online tool',
      'bcrypt generator without running server locally',
    ],
    searchVolume: 5000,
    label: '',
  },
  {
    id: 'base64-to-pdf',
    name: 'Base64 to PDF',
    description: 'Convert Base64 encoded data to PDF files and download them',
    icon: '📄',
    route: '/tools/base64-to-pdf',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'pdf',
      'convert',
      'download',
      'decode',
      'file',
      'document',
      'viewer',
      'preview',
      'base64 to pdf',
      'base64 decode pdf',
      'base64 string',
      'pdf converter',
      'online',
      'free',
    ],
    longTailKeywords: [
      'base64 to pdf converter online free no signup',
      'decode base64 string to pdf online free',
      'convert base64 pdf to file download free',
      'base64 to pdf decoder no registration required',
      'how to convert base64 encoded pdf to file',
      'how to decode base64 pdf from api response',
      'how to download pdf from base64 data uri',
      'base64 to pdf with in-browser preview free',
      'decode base64 pdf from rest api response online',
      'base64 data uri to pdf file converter free',
      'best free base64 to pdf converter online tool',
      'decode base64 pdf without running backend code',
    ],
    searchVolume: 7000,
    label: '',
  },
  {
    id: 'base64-to-gif',
    name: 'Base64 to GIF',
    description:
      'Convert Base64 encoded data to GIF images and download them with preview',
    icon: '🎞️',
    route: '/tools/base64-to-gif',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'gif',
      'image',
      'convert',
      'download',
      'decode',
      'animation',
    ],
    longTailKeywords: [
      'base64 to gif converter online free',
      'convert base64 string to gif image',
      'decode base64 to gif file download',
      'base64 animated gif decoder online',
      'how to convert base64 to gif image',
      'base64 to gif decoder with instant preview',
      'save base64 as gif file no registration',
      'base64 data uri to gif converter',
      'online base64 to gif converter no upload',
      'convert base64 to animated gif free',
      'decode base64 gif from api response',
      'free base64 to gif decoder client side',
    ],
    searchVolume: 1800,
    label: '',
  },
  {
    id: 'base64-to-png',
    name: 'Base64 to PNG',
    description:
      'Convert Base64 encoded data to PNG images with instant preview and download',
    icon: '🖼️',
    route: '/tools/base64-to-png',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'png',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    longTailKeywords: [
      'base64 to png converter online free',
      'convert base64 string to png image',
      'decode base64 to png file download',
      'base64 png decoder with instant preview',
      'how to convert base64 to png image',
      'base64 to png transparent background preview',
      'save base64 as png file no registration',
      'base64 data uri to png converter',
      'online base64 to png converter no upload',
      'convert base64 to png with alpha channel',
      'decode base64 png from api response',
      'free base64 to png decoder client side',
    ],
    searchVolume: 3800,
    label: '',
  },
  {
    id: 'base64-to-jpg',
    name: 'Base64 to JPG',
    description:
      'Convert Base64 encoded data to JPG/JPEG images with instant preview and download',
    icon: '📸',
    route: '/tools/base64-to-jpg',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'jpg',
      'jpeg',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    longTailKeywords: [
      'base64 to jpg converter online free',
      'convert base64 string to jpeg image',
      'decode base64 to jpg file download',
      'base64 jpeg decoder with instant preview',
      'how to convert base64 to jpg image',
      'base64 to jpeg quality estimation preview',
      'save base64 as jpg file no registration',
      'base64 data uri to jpg converter',
      'online base64 to jpeg converter no upload',
      'decode base64 jpeg from api response',
      'free base64 to jpg no signup no upload',
      'free base64 to jpeg decoder client side',
    ],
    searchVolume: 4500,
    label: '',
  },
  {
    id: 'base64-to-webp',
    name: 'Base64 to WebP',
    description:
      'Convert Base64 encoded data to WebP images with instant preview, transparency support and compression info',
    icon: '⚡',
    route: '/tools/base64-to-webp',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'webp',
      'image',
      'convert',
      'download',
      'decode',
      'modern',
      'compression',
      'lossy',
      'lossless',
    ],
    longTailKeywords: [
      'base64 to webp converter online free',
      'convert base64 string to webp image',
      'decode base64 to webp file',
      'base64 webp decoder online',
      'how to convert base64 to webp',
      'base64 to webp with instant preview and download',
      'decode animated webp from base64 string',
      'base64 data uri to webp converter',
      'online base64 to webp converter no upload',
      'convert base64 to webp with transparency',
      'free base64 to webp converter no signup required',
      'browser based base64 to webp decoder tool',
    ],
    searchVolume: 2200,
    label: '',
  },
  {
    id: 'excel-filter',
    name: 'Excel Filter Tool',
    description:
      'Upload Excel files and apply dynamic filters to tables with search, sort, and export capabilities',
    icon: '📊',
    route: '/tools/excel-filter',
    categories: ['data'],
    keywords: [
      'excel',
      'filter',
      'spreadsheet',
      'table',
      'data',
      'search',
      'sort',
      'export',
      'csv',
      'xlsx',
      'query',
      'analyze',
      'viewer',
      'browser',
      'online',
    ],
    longTailKeywords: [
      'excel filter tool online free no signup',
      'filter excel file online free no registration',
      'view and filter xlsx file online free',
      'analyze excel data online without excel free',
      'how to filter excel spreadsheet online',
      'how to search and filter excel data online',
      'how to export filtered excel data to csv free',
      'excel filter and sort tool with multiple conditions',
      'online excel viewer with advanced filter options',
      'filter large excel file online without excel installed',
      'best free excel filter tool online no account',
      'excel data filter without microsoft office subscription',
    ],
    searchVolume: 8000,
    label: '',
  },

  // Text & Format Tools
  {
    id: 'instagram-font-generator',
    name: 'Instagram Font Generator',
    description:
      'Generate stylized Unicode fonts for Instagram, WhatsApp, and social media bios',
    icon: '✨',
    route: '/tools/instagram-font-generator',
    categories: ['social', 'text'],
    keywords: [
      'instagram',
      'font',
      'generator',
      'unicode',
      'text',
      'style',
      'fancy',
      'bio',
      'whatsapp',
      'social',
      'media',
      'bold',
      'italic',
      'cursive',
      'monospace',
      'aesthetic',
      'fonts for instagram',
      'instagram bio fonts',
      'fancy text generator',
      'unicode text',
      'stylish text',
      'cool fonts',
      'text decorator',
    ],
    longTailKeywords: [
      'instagram font generator copy and paste free',
      'fancy text generator for social media bios',
      'how to change font on instagram bio',
      'cool fonts for tiktok bio copy paste',
      'aesthetic text generator for instagram captions',
      'stylish unicode fonts for whatsapp status',
      'best free font generator for instagram profiles',
      'instagram bio fonts with character counter',
      'cursive bold italic fonts copy paste online',
      'fancy font styles for twitter profile bio',
      'free text style generator no app download',
      'font changer online with platform compatibility',
    ],
    searchVolume: 95000,
    label: '',
  },
  {
    id: 'linkedin-post-formatter',
    name: 'LinkedIn Post Formatter',
    description:
      'Format LinkedIn posts with bold, italic, and special characters using Unicode. Increase engagement with professional formatting.',
    icon: '💼',
    route: '/tools/linkedin-post-formatter',
    categories: ['social', 'text'],
    keywords: [
      'linkedin',
      'post',
      'formatter',
      'bold',
      'italic',
      'unicode',
      'text',
      'formatting',
      'social',
      'media',
      'professional',
      'engagement',
      'bullet',
      'points',
      'linkedin post',
      'linkedin formatting',
      'linkedin bold text',
    ],
    longTailKeywords: [
      'linkedin post formatter online free',
      'linkedin bold text generator no signup required',
      'format linkedin post with bold and italic free',
      'linkedin text formatter for more engagement online',
      'how to make bold text in linkedin posts',
      'how to format linkedin posts with bullet points',
      'how to add bold italic text to linkedin posts',
      'linkedin post formatter with character counter',
      'linkedin unicode text formatter for professionals',
      'linkedin post formatter with mobile preview free',
      'best free linkedin post formatter online tool',
      'linkedin text formatter without third party app',
    ],
    searchVolume: 5000,
    label: '',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description:
      'Compare files and code with advanced diff features and syntax highlighting',
    icon: '📝',
    route: '/tools/text-diff',
    categories: ['text', 'dev'],
    keywords: [
      'diff',
      'compare',
      'text',
      'difference',
      'merge',
      'patch',
      'git',
      'code',
      'file',
    ],
    longTailKeywords: [
      'text diff checker online free no signup',
      'compare two texts online free no registration',
      'diff checker online free for code and documents',
      'find differences between two texts online free',
      'how to compare two code files online free',
      'how to find differences between two text files',
      'how to do git style diff comparison online',
      'text diff tool with side by side view online',
      'code diff checker with syntax highlighting free',
      'compare document versions online before merging',
      'best free diff checker online for developers',
      'compare texts without installing git or diff tool',
    ],
    searchVolume: 60000,
    label: '',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description:
      'Edit and preview Markdown with live rendering, export to HTML/PDF, and comprehensive statistics',
    icon: '📖',
    route: '/tools/markdown-preview',
    categories: ['text', 'formatters'],
    keywords: [
      'markdown',
      'preview',
      'html',
      'convert',
      'format',
      'editor',
      'gfm',
      'github',
      'export',
      'pdf',
    ],
    longTailKeywords: [
      'markdown preview editor online free no signup',
      'markdown editor with live preview free online',
      'markdown previewer online free no registration',
      'markdown to html converter with live preview free',
      'how to preview markdown online before committing',
      'how to write markdown with live html preview',
      'how to export markdown to pdf online free',
      'markdown editor with github flavored markdown support',
      'markdown previewer with export to html and pdf',
      'online markdown editor with auto save and statistics',
      'best free markdown preview editor online tool',
      'preview markdown without installing vscode or obsidian',
    ],
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with live matching',
    icon: '🔍',
    route: '/tools/regex-tester',
    categories: ['text'],
    keywords: ['regex', 'regexp', 'pattern', 'test', 'match'],
    longTailKeywords: [
      'regex tester online free no signup',
      'test regular expression online free no registration',
      'regex debugger online free instant results',
      'online regex tester with real time matching',
      'how to test regex pattern online free',
      'how to debug regular expression with live feedback',
      'how to match groups in regex online free',
      'regex tester with capture group details online',
      'regex tester with multiline and global flag support',
      'test email validation regex pattern online free',
      'best free online regex tester and debugger',
      'test regex without installing code editor or ide',
    ],
    searchVolume: 39000,
    label: '',
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID/GUID in various formats (v1, v4, etc.)',
    icon: '🆔',
    route: '/tools/uuid-generator',
    categories: ['generators'],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    longTailKeywords: [
      'uuid generator online free no signup',
      'generate uuid v4 online free no registration',
      'bulk uuid generator online free no account',
      'guid generator online free instant results',
      'how to generate uuid for database primary key',
      'how to create unique identifier for javascript app',
      'how to generate multiple uuids at once online',
      'uuid v4 generator with bulk export option free',
      'uuid generator for api testing and development',
      'generate uuid without installing node or python',
      'best free uuid guid generator online tool',
      'uuid generator without signing up or creating account',
    ],
    searchVolume: 100000,
    label: '',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords with customizable options',
    icon: '🔑',
    route: '/tools/password-generator',
    categories: ['generators'],
    keywords: ['password', 'generate', 'secure', 'random', 'strong'],
    longTailKeywords: [
      'password generator online free no signup',
      'strong password generator free no registration',
      'secure random password generator online free',
      'generate strong password for account security',
      'how to generate secure random password online',
      'how to create strong password with special characters',
      'how to make unique password for every account',
      'password generator with custom length and symbols',
      'password generator for website accounts free online',
      'memorable passphrase generator free online tool',
      'best free password generator online no account',
      'password generator without installing password manager',
    ],
    searchVolume: 350000,
    label: '',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description:
      'Generate QR codes with advanced customization, logos, batch processing and developer tools',
    icon: '📱',
    route: '/tools/qr-generator',
    categories: ['generators', 'dev', 'web'],
    keywords: [
      'qr',
      'code',
      'generate',
      'barcode',
      'scan',
      'wifi',
      'vcard',
      'batch',
      'svg',
      'logo',
      'api',
      'developer',
    ],
    longTailKeywords: [
      'qr code generator online free no signup',
      'generate qr code for url free no registration',
      'qr code maker free online no watermark',
      'create qr code for website link free',
      'how to generate qr code for wifi password',
      'how to create qr code with logo embedded',
      'how to make qr code for business card free',
      'qr code generator with logo and custom colors',
      'batch qr code generator from csv file free',
      'qr code generator for vcard contact sharing',
      'best free qr code generator online no account',
      'qr code creator without installing app or software',
    ],
    searchVolume: 550000,
    label: '',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description:
      'Generate all types of barcodes - EAN, UPC, Code 128, QR codes, Data Matrix and more with customization',
    icon: '📊',
    route: '/tools/barcode-generator',
    categories: ['generators', 'dev'],
    keywords: [
      'barcode',
      'generator',
      'ean',
      'upc',
      'code 128',
      'code 39',
      'qr code',
      'data matrix',
      'isbn',
      'retail',
      'product',
      'inventory',
      'shipping',
      'warehouse',
      'label',
      'scanner',
      'batch',
      'svg',
      'png',
      'pdf',
    ],
    longTailKeywords: [
      'free online barcode generator no signup required',
      'bulk barcode generator from excel csv free',
      'ean-13 barcode generator free online',
      'upc-a barcode generator online free',
      'code 128 barcode generator free download png svg',
      'how to create barcode for my product free',
      'barcode generator for retail product labels',
      'barcode generator for inventory management free',
      'batch barcode creator from csv file online',
      'barcode label maker print at home free',
      'isbn barcode generator free online no registration',
      'barcode generator high resolution print quality 300 dpi',
    ],
    searchVolume: 350000,
    label: '',
  },

  // Web & Design Tools
  {
    id: 'color-picker',
    name: 'Color Picker',
    description:
      'Professional color picker with palettes, contrast checker and format conversion',
    icon: '🎨',
    route: '/tools/color-picker',
    categories: ['web', 'dev'],
    keywords: [
      'color',
      'picker',
      'hex',
      'rgb',
      'hsl',
      'hsv',
      'cmyk',
      'palette',
      'generator',
      'contrast',
      'checker',
      'wcag',
      'accessibility',
      'css',
      'tailwind',
      'material',
      'design',
      'eyedropper',
      'gradient',
      'harmony',
      'complementary',
      'triadic',
      'analogous',
      'color blindness',
      'lab',
      'pantone',
    ],
    longTailKeywords: [
      'color picker online free no signup',
      'hex color picker with rgb and hsl output free',
      'online color picker tool no registration required',
      'color picker for web designers free online',
      'how to pick colors for website design online',
      'how to convert hex color to rgb online',
      'how to check color contrast for accessibility wcag',
      'color picker with wcag contrast checker free',
      'color picker with tailwind css palette generator',
      'color palette generator from single color free',
      'best free online color picker for developers',
      'color picker without installing software browser based',
    ],
    searchVolume: 350000,
    label: '',
  },
  {
    id: 'color-format-converter',
    name: 'Color Format Converter',
    description:
      'Convert colors between HEX, RGB, HSL, HSV, and CMYK formats with palette generation and contrast checker',
    icon: '🌈',
    route: '/tools/color-format-converter',
    categories: ['web', 'generators', 'dev'],
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'hsl to hex',
      'hsv to rgb',
      'cmyk converter',
      'color format',
      'hex converter',
      'rgb converter',
      'color code',
      'color transformation',
      'color palette generator',
      'color shades',
      'color tints',
      'wcag contrast',
      'accessibility',
      'css colors',
      'color picker',
      'web colors',
      'design colors',
    ],
    longTailKeywords: [
      'hex to rgb color converter online free',
      'color converter hex rgb hsl online free',
      'cmyk to hex color converter online free',
      'color format converter no signup required',
      'how to convert hex to rgb color online',
      'how to convert rgb to cmyk for print',
      'what is the difference between hex rgb and hsl',
      'color converter with css variable export',
      'color converter with wcag contrast checker',
      'color palette generator from hex code',
      'best free color converter for web designers',
      'color converter with figma color values',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'image-optimizer',
    name: 'Image Optimizer',
    description: 'Compress and optimize images for web use',
    icon: '🖼️',
    route: '/tools/image-optimizer',
    categories: ['web'],
    keywords: ['image', 'optimize', 'compress', 'resize', 'webp'],
    longTailKeywords: [
      'image optimizer online free no signup',
      'compress image online free no registration',
      'reduce image file size online free no upload',
      'optimize jpg png webp online free tool',
      'how to compress image for website online free',
      'how to reduce image size without losing quality',
      'how to optimize images for faster page speed',
      'image compressor with quality control slider free',
      'batch image optimizer online free no watermark',
      'optimize images for web without photoshop free',
      'best free image optimizer online for developers',
      'compress images without installing image editing software',
    ],
    isNew: true,
    searchVolume: 150000,
    label: 'coming-soon',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description:
      'Generate complete favicon packages with all sizes and formats',
    icon: '🖥️',
    route: '/tools/favicon-generator',
    categories: ['web', 'generators'],
    keywords: [
      'favicon',
      'icon',
      'apple-touch-icon',
      'android-chrome',
      'website-icon',
      'ico',
      'png',
      'image',
    ],
    longTailKeywords: [
      'favicon generator online free no signup',
      'create favicon from image online free no registration',
      'favicon maker free instant no account required',
      'generate ico png favicon for website free',
      'how to create favicon for website online free',
      'how to generate all favicon sizes from one image',
      'how to make apple touch icon from logo free',
      'favicon generator with all sizes ico png svg',
      'favicon generator with html implementation code',
      'create android chrome icon for web app free',
      'best free favicon generator online for websites',
      'favicon maker without installing image editing software',
    ],
    isNew: true,
    searchVolume: 32000,
    label: '',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description:
      'Create beautiful CSS gradients with visual editor, presets and real-time preview',
    icon: '🌈',
    route: '/tools/gradient-generator',
    categories: ['web', 'generators'],
    keywords: [
      'gradient',
      'css',
      'linear',
      'radial',
      'conic',
      'color',
      'background',
      'design',
      'web',
      'ui',
      'tailwind',
      'svg',
      'maker',
      'tool',
      'generator',
    ],
    longTailKeywords: [
      'css gradient generator online free no signup',
      'how to create css gradient background for website',
      'how to make linear gradient css background online',
      'best free css gradient generator online tool',
      'css gradient generator with multiple color stops',
      'css gradient generator with tailwind css export',
      'free linear radial conic css gradient generator',
      'css gradient code generator copy paste instantly',
      'gradient background generator for website free',
      'css gradient generator with svg export online',
      'css gradient generator for ui design backgrounds',
      'css gradient maker online free no login',
    ],
    searchVolume: 40000,
    label: '',
  },

  // Dev Utilities
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description:
      'Advanced JSON validation with schema support, error reporting, and security checks',
    icon: '✅',
    route: '/tools/json-validator',
    categories: ['dev', 'data'],
    keywords: [
      'json',
      'validator',
      'schema',
      'validate',
      'check',
      'format',
      'jsonschema',
      'draft',
      'parser',
      'syntax',
      'error',
      'linter',
      'api',
      'development',
      'security',
      'audit',
      'compliance',
      'structure',
      'verification',
      'testing',
    ],
    longTailKeywords: [
      'json validator online free no signup',
      'validate json online free no registration required',
      'json syntax checker free instant online',
      'check if json is valid online free no account',
      'how to validate json schema online free',
      'how to check json syntax errors online',
      'how to validate json against json schema',
      'json validator with json schema draft 7 support',
      'json validator with detailed error messages online',
      'json validator for api response testing free',
      'best free json validator online with schema support',
      'validate json without installing code editor or tools',
    ],
    searchVolume: 90000,
    label: '',
  },
  {
    id: 'crontab-builder',
    name: 'Crontab Expression Builder',
    description:
      'Parse, build, and validate cron expressions with visual builder, presets, and next execution times',
    icon: '⏰',
    route: '/tools/crontab-builder',
    categories: ['dev'],
    keywords: [
      'crontab',
      'cron',
      'scheduler',
      'unix',
      'linux',
      'automation',
      'parser',
      'builder',
      'expression',
    ],
    longTailKeywords: [
      'crontab builder online free no signup',
      'cron expression builder online free no registration',
      'cron job scheduler generator free instant online',
      'build crontab expression with visual editor free',
      'how to build cron expression for scheduled job',
      'how to parse cron expression to human readable',
      'how to schedule linux cron job expression online',
      'crontab expression builder with next run time preview',
      'cron job expression generator with common presets',
      'crontab parser and validator online free tool',
      'best free crontab builder online no account needed',
      'build cron schedule without remembering cron syntax',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'list-compare',
    name: 'List Compare & Diff Tool',
    description:
      'Advanced list comparison with set operations, fuzzy matching, and developer-friendly output formats',
    icon: '📋',
    route: '/tools/list-compare',
    categories: ['dev', 'text'],
    keywords: [
      'list compare',
      'diff lists',
      'set operations',
      'compare arrays',
      'list difference',
      'intersection',
      'union',
      'venn diagram',
      'array diff',
      'list merger',
      'duplicate finder',
      'fuzzy matching',
      'string comparison',
      'data analysis',
      'csv compare',
      'json compare',
      'package dependencies',
      'git files',
      'code compare',
    ],
    longTailKeywords: [
      'compare two lists online free',
      'compare two lists find differences free',
      'list comparison tool no signup required',
      'compare two lists without excel online',
      'how to compare two lists online',
      'how to find items only in one list',
      'how to find common items between two lists',
      'list comparison tool with venn diagram',
      'compare lists find intersection union difference',
      'compare two lists find duplicates online',
      'best free list diff tool online',
      'list comparison tool for data analysis',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description:
      'Convert cURL commands to production-ready code in any programming language with error handling and type safety',
    icon: '🔄',
    route: '/tools/curl-to-code',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to code',
      'curl converter',
      'curl to javascript',
      'curl to python',
      'http client generator',
      'api code generator',
      'curl to axios',
      'curl to fetch',
      'curl to golang',
      'curl to java',
      'curl to csharp',
      'curl to php',
      'curl to ruby',
      'rest api converter',
      'http request converter',
      'postman to code',
      'har to code',
      'api client generator',
      'sdk generator',
    ],
    longTailKeywords: [
      'curl to code converter online free',
      'convert curl command to python requests',
      'curl to javascript fetch code generator',
      'curl to axios node js converter online',
      'how to convert curl to golang http request',
      'curl to php guzzle code converter free',
      'best free curl to code converter no signup',
      'convert curl command to multiple languages online',
      'curl to python javascript go code generator',
      'curl converter with error handling async await',
      'convert api curl example to production code',
      'browser based curl to code converter private secure',
    ],
    searchVolume: 10000,
    label: '',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Converter',
    description:
      'Convert JSON to TypeScript interfaces with smart type inference, optional properties, and nested interface support',
    icon: '🔧',
    route: '/tools/json-to-typescript',
    categories: ['data', 'dev', 'generators'],
    keywords: [
      'json to typescript',
      'typescript interface generator',
      'json to interface',
      'type generator',
      'typescript types from json',
      'interface generator',
      'typescript converter',
      'json parser',
      'type inference',
      'typescript definitions',
      'api types',
      'type safety',
      'typescript interfaces',
      'json schema',
      'type generation',
      'developer tools',
      'code generator',
      'typescript typing',
      'json typing',
      'interface extractor',
    ],
    longTailKeywords: [
      'json to typescript converter online free',
      'generate typescript interfaces from json data',
      'json to ts interface generator with nested objects',
      'convert api response to typescript types online',
      'json to typescript with optional properties',
      'how to convert json to typescript automatically',
      'json to zod schema generator online free',
      'best free json to typescript interface generator',
      'json to typescript converter with union types',
      'generate typescript types from json api response',
      'json to typescript with enum detection and readonly',
      'convert json schema to typescript interfaces online',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier/Beautifier',
    description:
      'Minify, beautify and optimize CSS code with advanced compression options for production-ready stylesheets',
    icon: '🎨',
    route: '/tools/css-minifier',
    categories: ['formatters', 'dev', 'web'],
    keywords: [
      'css minifier',
      'css beautifier',
      'css formatter',
      'css compressor',
      'minimize css',
      'css optimization',
      'reduce css size',
      'css prettify',
      'css minify',
      'compress css',
      'css optimizer',
      'css cleaner',
      'production css',
      'css tools',
    ],
    longTailKeywords: [
      'css minifier online free no signup',
      'how to minify css file for production website',
      'free online css minifier compressor tool',
      'how to minify css for faster website performance',
      'minify css to improve page load speed online',
      'css minifier and beautifier online free',
      'how to reduce css file size without breaking styles',
      'css minifier with vendor prefix and media query optimization',
      'best free css minifier online no registration',
      'minify css for google pagespeed insights online',
      'css minifier beautifier with color compression',
      'compress css stylesheet online free instant',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'js-minifier',

    name: 'JavaScript Minifier/Beautifier',
    description:
      'Minify, beautify and optimize JavaScript code with ES6+ support, source maps, and advanced compression',
    icon: '⚡',
    route: '/tools/js-minifier',
    categories: ['formatters', 'dev'],
    keywords: [
      'javascript minifier',
      'js minifier',
      'javascript beautifier',
      'js formatter',
      'compress javascript',
      'minify js',
      'javascript optimizer',
      'js compression',
      'uglify js',
      'terser',
      'webpack optimizer',
      'production js',
      'bundle size',
      'tree shaking',
      'dead code elimination',
      'source maps',
      'obfuscation',
      'es6 minifier',
      'modern javascript',
    ],
    longTailKeywords: [
      'javascript minifier online free',
      'minify javascript online free no signup',
      'javascript minifier and beautifier online',
      'compress javascript code online free',
      'how to minify javascript online',
      'how to reduce javascript bundle size online',
      'minify javascript code to improve website speed',
      'javascript minifier with es6 es2024 support',
      'javascript minifier with source maps online',
      'minify javascript for production bundle optimization',
      'best free javascript minifier tool online',
      'uglify js alternative online free',
    ],
    searchVolume: 22000,
    label: '',
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML to JSON Converter',
    description:
      'Convert between YAML and JSON formats with validation, type handling, and advanced formatting',
    icon: '🔄',
    route: '/tools/yaml-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'yaml',
      'json',
      'converter',
      'parser',
      'formatter',
      'yaml to json',
      'json to yaml',
      'data transformation',
      'config converter',
      'kubernetes',
      'docker',
      'docker compose',
      'ci cd',
      'github actions',
      'ansible',
      'swagger',
      'openapi',
      'multi document',
      'anchors',
      'aliases',
    ],
    longTailKeywords: [
      'yaml to json converter online free',
      'json to yaml converter online free',
      'yaml to json converter no signup required',
      'convert yaml to json in browser instantly',
      'how to convert yaml to json online',
      'convert yaml to json without installing software',
      'how to convert kubernetes yaml to json',
      'yaml to json converter for kubernetes manifests',
      'yaml to json converter for docker compose files',
      'bidirectional yaml json converter online',
      'best free yaml to json converter online',
      'yaml to json converter with syntax validation',
    ],
    searchVolume: 18000,
    label: '',
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    description:
      'Validate YAML syntax with detailed error messages, line numbers, and support for YAML 1.1 and 1.2 specifications',
    icon: '✅',
    route: '/tools/yaml-validator',
    categories: ['data', 'dev'],
    keywords: [
      'yaml',
      'validator',
      'syntax',
      'checker',
      'linter',
      'yaml lint',
      'yaml check',
      'yaml syntax',
      'validate yaml',
      'yaml error',
      'kubernetes',
      'docker compose',
      'config validation',
      'yaml 1.1',
      'yaml 1.2',
    ],
    longTailKeywords: [
      'yaml validator online free no signup',
      'how to validate yaml file syntax online',
      'free yaml syntax checker no registration required',
      'yaml validator for kubernetes manifests online',
      'how to check yaml syntax errors with line numbers',
      'yaml validator for docker compose and github actions',
      'best free yaml validator online tool',
      'yaml lint checker online free instant results',
      'validate yaml kubernetes manifest before deployment',
      'yaml syntax checker for ansible and helm charts',
      'yaml validator with duplicate key detection online',
      'check yaml file for errors without installing software',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description:
      'Convert between Unix timestamps and human-readable dates with timezone support and batch processing',
    icon: '⏰',
    route: '/tools/unix-timestamp-converter',
    categories: ['data', 'dev'],
    keywords: [
      'unix',
      'timestamp',
      'epoch',
      'converter',
      'date',
      'time',
      'timezone',
      'utc',
      'milliseconds',
      'batch',
      'convert',
      'unix time',
      'epoch time',
      'datetime',
      'iso',
      'rfc',
      'posix',
    ],
    longTailKeywords: [
      'unix timestamp converter online free no signup',
      'how to convert unix timestamp to date online',
      'epoch to date converter with timezone support',
      'convert epoch time to human readable date free',
      'unix timestamp to date converter milliseconds seconds',
      'convert unix timestamp to date javascript python',
      'best free epoch unix timestamp converter online',
      'epoch time to date converter no registration',
      'unix timestamp converter for api debugging online',
      'convert epoch to iso 8601 date format online',
      'current unix timestamp to human readable date',
      'unix epoch time converter without signup instant',
    ],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'eml-to-html',
    name: 'EML to HTML Converter',
    description:
      'Convert EML email files to HTML with header extraction, attachment handling, and multi-view rendering',
    icon: '📧',
    route: '/tools/eml-to-html',
    categories: ['data', 'dev', 'formatters'],
    keywords: [
      'eml',
      'email',
      'html',
      'converter',
      'mime',
      'rfc822',
      'email parser',
      'eml viewer',
      'email to html',
      'email converter',
      'mime parser',
      'email headers',
      'email attachments',
      'email migration',
      'email forensics',
      'email template',
      'mailbox',
      'outlook',
      'thunderbird',
      'message',
      'rfc2822',
      'multipart',
      'base64',
      'quoted-printable',
    ],
    longTailKeywords: [
      'eml to html converter online free',
      'convert eml file to html no signup required',
      'open eml file online without outlook free',
      'eml viewer online free no registration',
      'how to convert eml email file to html',
      'how to open eml file without email client',
      'how to view eml file in browser online',
      'eml to html converter with attachment extraction',
      'eml file viewer with header parsing online',
      'convert outlook email eml file to html free',
      'best free eml to html converter online tool',
      'eml converter without installing email software',
    ],
    searchVolume: 2000,
    label: '',
  },
  {
    id: 'ai-prompt-token-counter',
    name: 'AI Prompt Token Counter',
    description:
      'Count tokens for AI prompts across GPT-4, Claude, Llama models with cost estimation and optimization',
    icon: '🤖',
    route: '/tools/ai-prompt-token-counter',
    categories: ['dev', 'generators', 'text'],
    keywords: [
      'token counter',
      'gpt token calculator',
      'claude tokens',
      'prompt tokens',
      'ai cost calculator',
      'token estimator',
      'openai tokens',
      'gpt-4 tokens',
      'llama tokens',
      'token count',
      'tokenizer',
      'api cost',
      'prompt optimization',
      'context window',
      'tiktoken',
      'ai pricing',
      'token visualization',
      'batch token count',
      'prompt engineering',
    ],
    longTailKeywords: [
      'ai token counter online free no signup',
      'count tokens for openai gpt-4 api calls',
      'how to count tokens before sending api request',
      'openai api cost calculator token pricing estimator',
      'claude token counter with cost estimation',
      'gpt-4 token counter and context window checker',
      'llm token calculator compare models pricing',
      'free tiktoken alternative online token counter',
      'prompt token counter for chatgpt claude gemini',
      'optimize prompt to reduce tokens and api costs',
      'ai api cost estimator multiple models comparison',
      'count tokens for prompt engineering and optimization',
    ],
    searchVolume: 20000,
    label: '',
  },

  // PDF Tools
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description:
      'Convert PDF files to editable Word (DOCX) format with preserved formatting',
    icon: '📄',
    route: '/tools/pdf-to-word',
    categories: ['pdf'],
    keywords: [
      'pdf',
      'word',
      'docx',
      'convert',
      'converter',
      'pdf to word',
      'pdf to docx',
      'document',
      'edit',
      'format',
      'export',
      'transformation',
      'office',
      'microsoft word',
      'libre office',
      'editable',
    ],
    longTailKeywords: [
      'pdf to word converter online free',
      'convert pdf to docx no signup required',
      'pdf to word converter free no watermark',
      'convert pdf to editable word document online free',
      'how to convert pdf to word without losing formatting',
      'how to convert pdf to word document online',
      'how to edit pdf by converting to word free',
      'pdf to word converter preserve formatting free',
      'pdf to docx converter with image extraction',
      'batch pdf to word converter online free',
      'best free pdf to word converter online tool',
      'convert pdf to word without adobe acrobat',
    ],
    searchVolume: 1000000,
    label: '',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description:
      'Convert multiple images (JPG, PNG, GIF, WebP) into a single PDF document with custom page sizes',
    icon: '🖼️',
    route: '/tools/image-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'image',
      'pdf',
      'convert',
      'jpg',
      'png',
      'gif',
      'webp',
      'image to pdf',
      'jpg to pdf',
      'png to pdf',
      'photo to pdf',
      'picture to pdf',
      'combine images',
      'merge images',
      'multiple images',
      'batch convert',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'image to pdf converter online free no signup',
      'how to combine multiple images into one pdf',
      'convert jpg png to pdf free no upload required',
      'merge multiple photos into one pdf document free',
      'jpg to pdf converter online free no watermark',
      'image to pdf converter with custom page size margins',
      'how to turn multiple pictures into a pdf file',
      'convert images to pdf without installing software',
      'combine jpg png webp images into pdf online',
      'image to pdf converter for scanned documents online',
      'best free image to pdf converter online tool',
      'convert multiple photos to pdf a4 letter format',
    ],
    searchVolume: 300000,
    label: '',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description:
      'Convert JPG and JPEG images to PDF format with custom page sizes and layout options',
    icon: '🖼️',
    route: '/tools/jpg-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'jpg',
      'jpeg',
      'pdf',
      'convert',
      'jpg to pdf',
      'jpeg to pdf',
      'image to pdf',
      'photo to pdf',
      'picture to pdf',
      'jpg converter',
      'jpeg converter',
      'batch convert',
      'multiple jpg',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'convert jpg to pdf online free',
      'jpg to pdf converter without losing quality',
      'combine multiple jpg images into one pdf',
      'jpg to pdf converter no watermark free',
      'how to convert jpeg to pdf without software',
      'free online jpg to pdf no download required',
      'batch convert jpg to pdf online free',
      'jpg to pdf with custom page size options',
      'convert jpeg photos to pdf document free',
      'jpg to pdf no signup no registration needed',
      'merge jpg files into single pdf online',
      'secure browser based jpg to pdf converter',
    ],
    searchVolume: 1500000,
    label: '',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description:
      'Convert PNG images to PDF format with transparency support and custom page options',
    icon: '🖼️',
    route: '/tools/png-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'png',
      'pdf',
      'convert',
      'png to pdf',
      'image to pdf',
      'transparent',
      'transparency',
      'photo to pdf',
      'picture to pdf',
      'png converter',
      'batch convert',
      'multiple png',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'convert png to pdf online free',
      'png to pdf converter without losing quality',
      'combine multiple png images into one pdf',
      'png to pdf converter no watermark free',
      'how to convert png to pdf with transparency',
      'free online png to pdf no download required',
      'batch convert png to pdf online free',
      'png to pdf preserve transparent background',
      'merge png files into single pdf document',
      'png to pdf no signup no registration needed',
      'convert png screenshots to pdf document free',
      'secure browser based png to pdf converter',
    ],
    searchVolume: 600000,
    label: '',
  },
  {
    id: 'gif-to-pdf',
    name: 'GIF to PDF',
    description:
      'Convert GIF images to PDF format preserving quality with custom page sizes',
    icon: '🖼️',
    route: '/tools/gif-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'gif',
      'pdf',
      'convert',
      'gif to pdf',
      'image to pdf',
      'animated gif',
      'photo to pdf',
      'picture to pdf',
      'gif converter',
      'batch convert',
      'multiple gif',
      'page size',
      'a4',
      'letter',
    ],
    longTailKeywords: [
      'gif to pdf converter online free',
      'convert gif to pdf online no signup',
      'batch convert gif to pdf online free',
      'animated gif to pdf converter online free',
      'how to convert gif to pdf online',
      'how to turn gif images into pdf document',
      'how to convert animated gif to pdf free',
      'gif to pdf converter custom page size a4',
      'convert multiple gif files to one pdf',
      'gif to pdf converter with no file upload',
      'best free gif to pdf converter no watermark',
      'gif to pdf converter without adobe acrobat',
    ],
    searchVolume: 5000,
    label: '',
  },

  // Social Media Tools
  {
    id: 'whatsapp-link-generator',
    name: 'WhatsApp Link Generator',
    description:
      'Create WhatsApp click-to-chat links with pre-filled messages and QR codes',
    icon: '💬',
    route: '/tools/whatsapp-link-generator',
    categories: ['social', 'generators'],
    keywords: [
      'whatsapp',
      'link generator',
      'wa.me',
      'click to chat',
      'whatsapp link',
      'whatsapp api',
      'chat link',
      'whatsapp qr code',
      'business whatsapp',
      'whatsapp message',
      'wa link',
      'whatsapp shortcut',
      'contact link',
      'phone link',
      'messaging',
      'social media',
    ],
    searchVolume: 70000,
    longTailKeywords: [
      'whatsapp link generator online free',
      'create whatsapp click to chat link',
      'how to create wa.me link with message',
      'free whatsapp qr code generator with message',
      'whatsapp chat link generator with pre-filled message',
      'whatsapp link generator no registration required',
      'create whatsapp button for website free',
      'whatsapp direct message link without saving number',
      'whatsapp link for business card qr code',
      'how to make whatsapp link for website',
      'whatsapp short link generator for social media',
      'free whatsapp link creator with qr code',
    ],
    label: '',
  },
  {
    id: 'utm-builder',
    name: 'UTM Link Builder',
    description:
      'Create trackable URLs with UTM parameters for marketing campaigns, analytics, and link tracking',
    icon: '🔗',
    route: '/tools/utm-builder',
    categories: ['social', 'generators', 'web'],
    keywords: [
      'utm',
      'link builder',
      'url builder',
      'utm parameters',
      'campaign tracking',
      'utm generator',
      'google analytics',
      'utm tags',
      'marketing links',
      'utm source',
      'utm medium',
      'utm campaign',
      'link tracking',
      'campaign url',
      'url tracking',
      'analytics',
      'marketing',
      'social media tracking',
      'qr code',
      'short link',
    ],
    longTailKeywords: [
      'utm builder online free no signup',
      'google analytics campaign url builder free',
      'how to create utm parameters for tracking',
      'utm tag generator for social media campaigns',
      'utm link builder with saved templates',
      'bulk utm url generator for marketing teams',
      'free utm code generator for email campaigns',
      'utm builder for google analytics ga4',
      'create trackable links for social media ads',
      'campaign url builder with naming conventions',
      'utm parameter generator with presets and export',
      'best free utm builder alternative to google',
    ],
    searchVolume: 35000,
    label: '',
  },
  {
    id: 'youtube-timestamp-generator',
    name: 'YouTube Timestamp Generator',
    description:
      'Create YouTube timestamps and chapters with automatic link generation and time conversion',
    icon: '⏱️',
    route: '/tools/youtube-timestamp-generator',
    categories: ['social', 'generators'],
    keywords: [
      'youtube',
      'timestamp',
      'chapters',
      'youtube chapters',
      'video timestamp',
      'timestamp generator',
      'youtube time',
      'video chapters',
      'youtube link',
      'time converter',
      'hh:mm:ss',
      'video navigation',
      'youtube creator',
      'video description',
      'timestamp link',
    ],
    longTailKeywords: [
      'youtube timestamp generator online free',
      'how to add chapters to youtube video description',
      'youtube chapter generator free no signup',
      'create clickable timestamp links for youtube',
      'youtube timestamp link generator share video moment',
      'how to create youtube chapters for seo',
      'generate youtube video timestamps with labels',
      'youtube chapters format copy paste description',
      'free tool to make youtube video chapters',
      'youtube timestamp generator for podcast episodes',
      'create youtube chapters for long videos tutorials',
      'youtube video chapter maker with time converter',
    ],
    searchVolume: 6000,
    label: '',
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description:
      'Calculate Unix file permissions with visual grid, octal and symbolic notation converter',
    icon: '🔒',
    route: '/tools/chmod-calculator',
    categories: ['dev', 'generators'],
    keywords: [
      'chmod',
      'permissions',
      'linux',
      'unix',
      'file permissions',
      'chmod calculator',
      'chmod converter',
      'octal permissions',
      'symbolic permissions',
      'rwx',
      'read write execute',
      'owner group others',
      'chmod 755',
      'chmod 644',
      'chmod 777',
      'permission bits',
      'sysadmin',
      'server',
      'shell',
      'terminal',
    ],
    longTailKeywords: [
      'chmod calculator online free no signup',
      'linux file permissions calculator free online',
      'convert chmod octal to symbolic notation online',
      'chmod 755 644 777 permissions calculator free',
      'how to calculate chmod permissions online',
      'how to set linux file permissions using chmod',
      'how to convert octal to rwx permissions online',
      'chmod calculator with recursive flag option',
      'unix file permissions calculator with visual grid',
      'chmod permission calculator for web server files',
      'best free chmod calculator online no registration',
      'chmod calculator without installing linux terminal',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'htaccess-generator',
    name: 'Htaccess Generator',
    description:
      'Generate .htaccess files for Apache with redirects, security rules, caching, and URL rewriting',
    icon: '⚙️',
    route: '/tools/htaccess-generator',
    categories: ['dev', 'generators', 'web'],
    keywords: [
      'htaccess',
      'htaccess generator',
      'apache',
      'redirect',
      '301 redirect',
      '302 redirect',
      'url rewrite',
      'mod_rewrite',
      'security headers',
      'caching',
      'gzip compression',
      'force https',
      'www redirect',
      'custom error pages',
      'directory protection',
      'password protect',
      'hotlink protection',
      'ip blocking',
      'file access',
      'mime types',
      'server configuration',
      'web server',
      'seo redirect',
    ],
    longTailKeywords: [
      'htaccess generator online free no login required',
      'how to create htaccess file for apache redirects',
      'how to force https redirect in htaccess file',
      'free htaccess generator for apache redirects',
      'htaccess 301 redirect generator without coding',
      'how to set up 301 redirects in htaccess file',
      'htaccess generator with wordpress security rules',
      'best free htaccess generator online tool',
      'generate htaccess file without writing code',
      'htaccess redirect generator for website migration',
      'htaccess generator with gzip compression and caching',
      'htaccess generator for beginners no coding required',
    ],
    searchVolume: 8000,
    label: '',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description:
      'Generate placeholder text for designs, mockups, and layouts with customizable word, sentence, or paragraph count',
    icon: '📝',
    route: '/tools/lorem-ipsum-generator',
    categories: ['text', 'generators'],
    keywords: [
      'lorem ipsum',
      'lorem ipsum generator',
      'placeholder text',
      'dummy text',
      'filler text',
      'sample text',
      'text generator',
      'lipsum',
      'blind text',
      'greeking',
      'mockup text',
      'design placeholder',
      'paragraph generator',
      'random text',
      'latin text',
    ],
    longTailKeywords: [
      'lorem ipsum generator online free',
      'generate lorem ipsum paragraphs',
      'lorem ipsum copy paste',
      'placeholder text generator for designers',
      'dummy text generator for website mockup',
      'how to generate lorem ipsum text',
      'lorem ipsum generator with word count',
      'custom lorem ipsum paragraph generator',
      'free online placeholder text generator',
      'lorem ipsum sentences generator no signup',
      'generate dummy text for web design',
      'lipsum generator with custom length',
    ],
    searchVolume: 12500,
    label: '',
  },
  {
    id: 'string-case-converter',
    name: 'String Case Converter',
    description:
      'Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and more',
    icon: '🔤',
    route: '/tools/string-case-converter',
    categories: ['text', 'dev'],
    keywords: [
      'string case converter',
      'case converter',
      'camelCase',
      'PascalCase',
      'snake_case',
      'kebab-case',
      'CONSTANT_CASE',
      'SCREAMING_SNAKE_CASE',
      'Title Case',
      'Sentence case',
      'lowercase',
      'uppercase',
      'text transform',
      'variable naming',
      'code formatting',
      'naming convention',
      'string transformation',
      'text case',
      'convert case',
    ],
    longTailKeywords: [
      'string case converter online free no signup',
      'convert camelcase to snake case online free',
      'convert snake case to camelcase online free',
      'how to convert text to camelcase online',
      'how to convert variable names between cases online',
      'how to change camelcase to kebab case online',
      'camelcase to snake case converter for developers',
      'string case converter with batch conversion mode',
      'convert text case for code refactoring online free',
      'text case converter for javascript python naming',
      'best free string case converter for developers',
      'convert naming convention without writing code',
    ],
    searchVolume: 25000,
    label: '',
  },
  {
    id: 'binary-to-text',
    name: 'Binary to Text Converter',
    description:
      'Convert binary numbers to text and vice versa with support for ASCII, UTF-8, and hex formats',
    icon: '🔢',
    route: '/tools/binary-to-text',
    categories: ['encoding', 'data'],
    keywords: [
      'binary to text',
      'text to binary',
      'binary converter',
      'binary decoder',
      'binary encoder',
      'ascii binary',
      'binary string',
      'binary code',
      'binary translation',
      '01 to text',
      'binary ascii converter',
      'binary to ascii',
      'ascii to binary',
      'hex to binary',
      'binary to hex',
      'utf-8 binary',
    ],
    longTailKeywords: [
      'binary to text converter online free no signup',
      'convert binary to text online free no registration',
      'decode binary code to ascii text online free',
      'convert text to binary numbers online free',
      'how to convert binary to readable text online',
      'how to decode binary code from network packets',
      'how to convert ascii text to binary online free',
      'binary to text converter with utf-8 support',
      'text to binary encoder with hex conversion free',
      'binary code translator for computer science learning',
      'best free binary to text converter online tool',
      'binary decoder without installing programming environment',
    ],
    searchVolume: 27000,
    label: '',
  },
  {
    id: 'js-object-to-json',
    name: 'JavaScript Object to JSON',
    description:
      'Convert JavaScript objects to valid JSON with circular reference detection, function handling, and BigInt support',
    icon: '🔄',
    route: '/tools/js-object-to-json',
    categories: ['data', 'dev'],
    keywords: [
      'javascript to json',
      'js object to json',
      'object to json',
      'json converter',
      'javascript object converter',
      'js to json online',
      'convert js to json',
      'json stringify',
      'object serialization',
      'circular reference',
      'bigint json',
      'function to json',
      'undefined json',
      'javascript parser',
      'json generator',
    ],
    longTailKeywords: [
      'javascript object to json converter online free',
      'convert js object to json online free no signup',
      'js object literal to json converter no registration',
      'convert javascript object to valid json free online',
      'how to convert javascript object to json online',
      'how to stringify javascript object with special values',
      'how to handle circular references in json conversion',
      'js object to json converter with bigint support',
      'convert devtools copied object to valid json free',
      'javascript to json with function and undefined handling',
      'best free javascript object to json converter online',
      'convert js object to json without running node.js',
    ],
    searchVolume: 6000,
    label: '',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description:
      'Convert HTML to Markdown or Markdown to HTML with GFM table and code block support',
    icon: '🔄',
    route: '/tools/html-to-markdown',
    categories: ['text', 'formatters'],
    keywords: [
      'html to markdown',
      'markdown to html',
      'html to md',
      'html converter',
      'markdown converter',
      'html',
      'markdown',
      'convert',
      'md',
      'gfm',
      'github',
      'turndown',
      'wordpress to markdown',
      'notion markdown',
      'obsidian markdown',
      'copy html as markdown',
      'table',
      'code',
    ],
    longTailKeywords: [
      'html to markdown converter online free no signup',
      'convert html to markdown no registration required',
      'html to markdown converter free instant online',
      'paste html and get markdown free online tool',
      'how to convert html to markdown online',
      'how to convert wordpress html to markdown',
      'how to turn html into clean markdown for github',
      'html to markdown with github flavored markdown support',
      'html to markdown converter for notion and obsidian',
      'convert wysiwyg html output to markdown online',
      'best free html to markdown converter online',
      'html to markdown without installing node packages',
    ],
    searchVolume: 10000,
    label: '',
  },
];

// Group tools by category
export const categories: Category[] = [
  {
    id: 'data',
    name: 'Data & Conversion',
    description:
      'Transform and format data between different formats like JSON, CSV, XML, and SQL.',
    icon: '📊',
    tools: getToolsByCategory('data'),
  },
  {
    id: 'encoding',
    name: 'Encoding & Security',
    description:
      'Encode, decode, hash, and secure your data with various encryption methods.',
    icon: '🔐',
    tools: getToolsByCategory('encoding'),
  },
  {
    id: 'base64',
    name: 'Base64',
    description:
      'Convert Base64 encoded data to PDF, images, and other file formats with instant download and preview.',
    icon: '🔤',
    tools: getToolsByCategory('base64'),
  },
  {
    id: 'text',
    name: 'Text & Format',
    description:
      'Process, compare, and format text content with powerful text manipulation tools.',
    icon: '📝',
    tools: getToolsByCategory('text'),
  },
  {
    id: 'generators',
    name: 'Generators',
    description:
      'Generate UUIDs, passwords, QR codes, and other useful content for development.',
    icon: '⚡',
    tools: getToolsByCategory('generators'),
  },
  {
    id: 'web',
    name: 'Web & Design',
    description:
      'Tools for web developers and designers including color pickers and image optimization.',
    icon: '🎨',
    tools: getToolsByCategory('web'),
  },
  {
    id: 'dev',
    name: 'Dev Utilities',
    description:
      'Development utilities for testing APIs, validating schemas, and debugging code.',
    icon: '🔧',
    tools: getToolsByCategory('dev'),
  },
  {
    id: 'formatters',
    name: 'Formatters',
    description:
      'Format and beautify code, SQL, JSON, XML and other structured data.',
    icon: '🪄',
    tools: getToolsByCategory('formatters'),
  },
  {
    id: 'social',
    name: 'Social Media',
    description:
      'Tools for social media content creation, including Instagram, WhatsApp, Twitter, and Facebook.',
    icon: '📱',
    tools: getToolsByCategory('social'),
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description:
      'Professional PDF tools for conversion, editing, merging, splitting and optimization.',
    icon: '📄',
    tools: getToolsByCategory('pdf'),
  },
];

// Helper functions
export function getPopularTools(): Tool[] {
  return tools
    .sort((a, b) => b.searchVolume - a.searchVolume)
    .map((tool) => ({
      ...tool,
      keywords: tool.keywords || [], // Ensure keywords is always an array
    }));
}

export function searchTools(query: string): Tool[] {
  const searchTerm = query.toLowerCase();
  return tools
    .filter(
      (tool) =>
        tool.label !== 'coming-soon' &&
        (tool.name.toLowerCase().includes(searchTerm) ||
          tool.description.toLowerCase().includes(searchTerm) ||
          tool.keywords.some((keyword) =>
            keyword.toLowerCase().includes(searchTerm)
          ))
    )
    .sort((a, b) => b.searchVolume - a.searchVolume);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools
    .filter((tool) => {
      return tool.categories.includes(categoryId);
    })
    .sort((a, b) => {
      // First sort by searchVolume (descending), then by name (ascending) for deterministic order
      if (b.searchVolume !== a.searchVolume) {
        return b.searchVolume - a.searchVolume;
      }
      return a.name.localeCompare(b.name);
    });
}

// O(1) lookup map for tools by ID
export const toolsMap = new Map<string, Tool>(tools.map((t) => [t.id, t]));

export function getToolById(id: string): Tool | undefined {
  return toolsMap.get(id);
}

export function getCategoryColorClass(categoryColor: string): string {
  const colorClasses = {
    data: 'border-blue-500 bg-blue-50 dark:bg-blue-950',
    encoding: 'border-green-500 bg-green-50 dark:bg-green-950',
    text: 'border-purple-500 bg-purple-50 dark:bg-purple-950',
    generators: 'border-orange-500 bg-orange-50 dark:bg-orange-950',
    web: 'border-pink-500 bg-pink-50 dark:bg-pink-950',
    dev: 'border-yellow-500 bg-yellow-50 dark:bg-yellow-950',
    formatters: 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950',
    social: 'border-rose-500 bg-rose-50 dark:bg-rose-950',
    pdf: 'border-red-500 bg-red-50 dark:bg-red-950',
  };
  return (
    colorClasses[categoryColor as keyof typeof colorClasses] ||
    'border-blue-500 bg-blue-50 dark:bg-blue-950'
  );
}

export function getCategoryByTool(tool: Tool): Category | undefined {
  return categories.find((category) =>
    category.tools.some((t) => t.id === tool.id)
  );
}

export function getAllTools(): Tool[] {
  return tools;
}
