import 'server-only';

/**
 * Server-only SEO data for tools.
 *
 * Long-tail keywords are used ONLY for:
 *  - Meta keywords in <head> (server, generateMetadata)
 *  - JSON-LD schema (server, build-time)
 *
 * They have ZERO client-runtime value. Keeping them in lib/tools.ts caused
 * webpack to ship ~80KB raw of keyword strings inside every client route chunk.
 * See RIC-XXX investigation (Apr 2026 INP regression).
 *
 * To add new long-tail keywords for a tool, append an entry here keyed by tool id.
 * NEVER reintroduce longTailKeywords in lib/tools.ts.
 */
export const toolLongTailKeywords: Record<string, string[]> = {
  'number-base-converter': [
    'number base converter online free',
    'hex to decimal converter online',
    'binary to decimal converter free',
    'decimal to hex converter online',
    'how to convert hex to decimal',
    'how to convert binary to decimal',
    'how to convert decimal to hexadecimal',
    'base 2 to base 16 converter',
    'convert number to any base 2 to 36',
    "two's complement binary converter online",
    'best free number base converter online',
    'number base converter no signup',
  ],
  'json-formatter': [
    'json formatter online free no signup',
    'format json online free no registration required',
    'json beautifier online free instant',
    'pretty print json online free no download',
    'how to format minified json online',
    'how to validate json syntax online free',
    'how to beautify json for readability online',
    'json formatter with syntax highlighting free',
    'json formatter with key sorting options online',
    'json validator and formatter for api responses',
    'best free json formatter and validator online',
    'format json without installing code editor',
  ],
  'csv-to-json': [
    'csv to json converter online free no signup',
    'convert csv to json online free no registration',
    'csv to json converter free no download required',
    'convert csv file to json array online free',
    'how to convert csv to json online',
    'how to convert spreadsheet data to json format',
    'how to import csv data into json for api',
    'csv to json converter with custom delimiter support',
    'csv to json with automatic header detection free',
    'convert excel csv export to json for database',
    'best free csv to json converter online tool',
    'csv to json without installing python or node.js',
  ],
  'json-to-csv': [
    'json to csv converter online free',
    'convert json to csv for excel online free',
    'json to csv converter no signup required',
    'convert json to csv for google sheets',
    'how to convert json to csv online',
    'how to convert nested json to csv',
    'how to flatten json for csv export',
    'json to csv converter with custom delimiter',
    'json to csv converter for api responses',
    'flatten nested json to csv online free',
    'best free json to csv converter online',
    'json to csv converter without file upload',
  ],
  'sql-formatter': [
    'sql formatter online free no signup',
    'format sql query online free no registration',
    'sql beautifier online free instant results',
    'beautify sql query online free no download',
    'how to format sql query for readability online',
    'how to beautify minified sql query online free',
    'how to indent sql statement online free',
    'sql formatter for mysql postgresql sqlite online',
    'sql formatter with syntax highlighting free online',
    'sql query formatter for code review and documentation',
    'best free sql formatter online for all dialects',
    'format sql without installing database client software',
  ],
  'xml-formatter': [
    'xml formatter online free no signup',
    'format and beautify xml online free no registration',
    'xml formatter and validator free instant online',
    'minify xml file online free no upload',
    'how to format xml online for readability',
    'how to validate xml syntax online free',
    'how to beautify minified xml online',
    'xml formatter with xpath search support',
    'xml beautifier with namespace and schema support',
    'xml formatter for soap and rss feeds online',
    'best free xml formatter and validator online',
    'xml formatter without installing xml editor software',
  ],
  'xml-to-json-converter': [
    'xml to json converter online free',
    'convert xml to json no signup required',
    'xml to json online converter free no download',
    'how to convert xml to json online',
    'convert soap xml response to json online free',
    'how to parse xml and convert to json format',
    'how to convert rss feed xml to json data',
    'xml to json converter with namespace support',
    'xml to json converter with smart array detection',
    'convert xml to json for api integration free',
    'best free xml to json converter online tool',
    'xml to json converter without installing software',
  ],
  'base64-encode': [
    'base64 encoder decoder online free no signup',
    'encode text to base64 online free no registration',
    'decode base64 string to text online free',
    'base64 encoder for files and images online free',
    'how to encode text to base64 online',
    'how to decode base64 string to readable text',
    'how to convert image to base64 for html css',
    'base64 encoder with file upload support free',
    'base64 decoder with utf-8 and binary support',
    'base64 encode decode for api development free',
    'best free base64 encoder decoder online tool',
    'base64 converter without installing software',
  ],
  'url-encode': [
    'url encoder decoder online free no signup',
    'encode url online free no registration required',
    'decode percent encoded url online free',
    'url encode special characters online free tool',
    'how to url encode a string online',
    'how to decode url encoded string online free',
    'how to encode query parameters for api calls',
    'url encoder with full vs component encoding options',
    'decode encoded url parameters online free tool',
    'url encoder decoder for api and web development',
    'best free url encoder decoder online tool',
    'url encode decode without installing software',
  ],
  'html-encode-decode': [
    'html encode decode online free no signup',
    'encode html entities online free no registration',
    'decode html entities to plain text online free',
    'html entity encoder free instant online tool',
    'how to encode html special characters online',
    'how to decode html entities to readable text',
    'how to escape html for xss prevention online',
    'html encoder with named and decimal entities free',
    'html entity decoder with auto-detection online',
    'encode html for safe display in web pages free',
    'best free html encoder decoder online tool',
    'html encode decode without installing developer tools',
  ],
  'hash-generator': [
    'hash generator online free no signup',
    'generate md5 sha256 hash online free no registration',
    'sha256 hash generator free instant online',
    'md5 hash generator online free no account',
    'how to generate md5 hash for file verification',
    'how to compute sha256 hash online for free',
    'how to verify file integrity using hash online',
    'hash generator for text and files online free',
    'sha512 hash generator with clipboard copy free',
    'cryptographic hash generator for security auditing',
    'best free hash generator online md5 sha256 sha512',
    'generate checksum without installing hashing tools',
  ],
  'jwt-decoder': [
    'jwt decoder online free no signup',
    'decode jwt token online free no registration',
    'inspect jwt claims online free instant',
    'jwt decoder and validator online free tool',
    'how to decode jwt token online',
    'how to inspect jwt payload claims online free',
    'how to verify jwt expiration time online',
    'jwt decoder with claims analysis and validation',
    'jwt token inspector for debugging authentication',
    'decode json web token for api debugging free',
    'best free jwt decoder online security tool',
    'decode jwt without installing jwt library locally',
    'verify jwt signature online free',
    'jwt signature verifier online tool',
    'jwt token expiration checker online',
    'verify jwt hs256 signature online',
    'verify jwt rs256 public key online free',
    'jwt verifier in browser no server upload',
    'check jwt token validity and signature online',
    'jwt expiry countdown online tool',
    'jwt encoder online free no signup',
    'create jwt token online free no registration',
    'sign jwt online free instant',
    'jwt generator online free hs256 rs256',
    'how to create a jwt token online',
    'how to sign jwt online free no server',
    'jwt signer with hmac secret and rsa private key',
    'jwt encoder and decoder in the same tool',
    'generate signed jwt for testing api authentication',
    'jwt maker online free for developers',
    'jwt encoder with custom claims and expiration',
    'sign jwt hs256 with secret online browser based',
    'sign jwt rs256 with pem private key online',
    'sign jwt es256 ecdsa in browser no upload',
    'jwt builder online free test environment',
  ],
  'bcrypt-hash-generator': [
    'bcrypt hash generator online free no signup',
    'generate bcrypt password hash online free',
    'bcrypt hash generator no registration required',
    'bcrypt password hashing tool for developers free',
    'how to generate bcrypt hash for password storage',
    'how to verify bcrypt password hash online',
    'how to choose bcrypt cost factor rounds',
    'bcrypt hash generator with configurable rounds',
    'bcrypt password hash verifier online free',
    'bcrypt hash generator for node js php python',
    'best free bcrypt hash generator online tool',
    'bcrypt generator without running server locally',
  ],
  'rot13-caesar-cipher': [
    'rot13 encoder decoder online free no signup',
    'caesar cipher online free no registration',
    'rot13 decoder online free instant',
    'caesar cipher encoder with shift online free',
    'how to decode rot13 message online',
    'how to solve caesar cipher without knowing shift',
    'caesar cipher brute force all 25 rotations online',
    'rot13 text converter free no watermark',
    'caesar cipher decoder for ctf challenges',
    'rot13 generator for reddit spoiler tags',
    'best free caesar cipher tool online',
    'classical caesar cipher tool for cryptography learning',
  ],
  'base64-to-pdf': [
    'base64 to pdf converter online free no signup',
    'decode base64 string to pdf online free',
    'convert base64 pdf to file download free',
    'base64 to pdf decoder no registration required',
    'how to convert base64 encoded pdf to file',
    'how to decode base64 pdf from api response',
    'how to download pdf from base64 data uri',
    'base64 to pdf with in-browser preview free',
    'decode base64 pdf from rest api response online',
    'base64 data uri to pdf file converter free',
    'best free base64 to pdf converter online tool',
    'decode base64 pdf without running backend code',
  ],
  'base64-to-gif': [
    'base64 to gif converter online free',
    'convert base64 string to gif image',
    'decode base64 to gif file download',
    'base64 animated gif decoder online',
    'how to convert base64 to gif image',
    'base64 to gif decoder with instant preview',
    'save base64 as gif file no registration',
    'base64 data uri to gif converter',
    'online base64 to gif converter no upload',
    'convert base64 to animated gif free',
    'decode base64 gif from api response',
    'free base64 to gif decoder client side',
  ],
  'base64-to-png': [
    'base64 to png converter online free',
    'convert base64 string to png image',
    'decode base64 to png file download',
    'base64 png decoder with instant preview',
    'how to convert base64 to png image',
    'base64 to png transparent background preview',
    'save base64 as png file no registration',
    'base64 data uri to png converter',
    'online base64 to png converter no upload',
    'convert base64 to png with alpha channel',
    'decode base64 png from api response',
    'free base64 to png decoder client side',
  ],
  'base64-to-jpg': [
    'base64 to jpg converter online free',
    'convert base64 string to jpeg image',
    'decode base64 to jpg file download',
    'base64 jpeg decoder with instant preview',
    'how to convert base64 to jpg image',
    'base64 to jpeg quality estimation preview',
    'save base64 as jpg file no registration',
    'base64 data uri to jpg converter',
    'online base64 to jpeg converter no upload',
    'decode base64 jpeg from api response',
    'free base64 to jpg no signup no upload',
    'free base64 to jpeg decoder client side',
  ],
  'base64-to-webp': [
    'base64 to webp converter online free',
    'convert base64 string to webp image',
    'decode base64 to webp file',
    'base64 webp decoder online',
    'how to convert base64 to webp',
    'base64 to webp with instant preview and download',
    'decode animated webp from base64 string',
    'base64 data uri to webp converter',
    'online base64 to webp converter no upload',
    'convert base64 to webp with transparency',
    'free base64 to webp converter no signup required',
    'browser based base64 to webp decoder tool',
  ],
  'excel-filter': [
    'excel filter tool online free no signup',
    'filter excel file online free no registration',
    'view and filter xlsx file online free',
    'analyze excel data online without excel free',
    'how to filter excel spreadsheet online',
    'how to search and filter excel data online',
    'how to export filtered excel data to csv free',
    'excel filter and sort tool with multiple conditions',
    'online excel viewer with advanced filter options',
    'filter large excel file online without excel installed',
    'best free excel filter tool online no account',
    'excel data filter without microsoft office subscription',
  ],
  'instagram-font-generator': [
    'instagram font generator copy and paste free',
    'fancy text generator for social media bios',
    'how to change font on instagram bio',
    'cool fonts for tiktok bio copy paste',
    'aesthetic text generator for instagram captions',
    'stylish unicode fonts for whatsapp status',
    'best free font generator for instagram profiles',
    'instagram bio fonts with character counter',
    'cursive bold italic fonts copy paste online',
    'fancy font styles for twitter profile bio',
    'free text style generator no app download',
    'font changer online with platform compatibility',
  ],
  'linkedin-post-formatter': [
    'linkedin post formatter online free',
    'linkedin bold text generator no signup required',
    'format linkedin post with bold and italic free',
    'linkedin text formatter for more engagement online',
    'how to make bold text in linkedin posts',
    'how to format linkedin posts with bullet points',
    'how to add bold italic text to linkedin posts',
    'linkedin post formatter with character counter',
    'linkedin unicode text formatter for professionals',
    'linkedin post formatter with mobile preview free',
    'best free linkedin post formatter online tool',
    'linkedin text formatter without third party app',
  ],
  'text-diff': [
    'text diff checker online free no signup',
    'compare two texts online free no registration',
    'diff checker online free for code and documents',
    'find differences between two texts online free',
    'how to compare two code files online free',
    'how to find differences between two text files',
    'how to do git style diff comparison online',
    'text diff tool with side by side view online',
    'code diff checker with syntax highlighting free',
    'compare document versions online before merging',
    'best free diff checker online for developers',
    'compare texts without installing git or diff tool',
  ],
  'word-counter': [
    'word counter online free no signup',
    'character counter online free',
    'word and character count tool online',
    'count words characters and reading time',
    'how to count words in a text online',
    'how many words in my text',
    'reading time calculator by word count',
    'count characters without spaces online',
    'word counter with reading and speaking time',
    'count words sentences and paragraphs online',
    'free word counter alternative to microsoft word',
    'best free word counter for writers and students',
  ],
  'markdown-preview': [
    'markdown preview editor online free no signup',
    'markdown editor with live preview free online',
    'markdown previewer online free no registration',
    'markdown to html converter with live preview free',
    'how to preview markdown online before committing',
    'how to write markdown with live html preview',
    'how to export markdown to pdf online free',
    'markdown editor with github flavored markdown support',
    'markdown previewer with export to html and pdf',
    'online markdown editor with auto save and statistics',
    'best free markdown preview editor online tool',
    'preview markdown without installing vscode or obsidian',
  ],
  'regex-tester': [
    'regex tester online free no signup',
    'test regular expression online free no registration',
    'regex debugger online free instant results',
    'online regex tester with real time matching',
    'how to test regex pattern online free',
    'how to debug regular expression with live feedback',
    'how to match groups in regex online free',
    'regex tester with capture group details online',
    'regex tester with multiline and global flag support',
    'test email validation regex pattern online free',
    'best free online regex tester and debugger',
    'test regex without installing code editor or ide',
  ],
  'uuid-generator': [
    'uuid generator online free no signup',
    'generate uuid v4 online free no registration',
    'bulk uuid generator online free no account',
    'guid generator online free instant results',
    'how to generate uuid for database primary key',
    'how to create unique identifier for javascript app',
    'how to generate multiple uuids at once online',
    'uuid v4 generator with bulk export option free',
    'uuid generator for api testing and development',
    'generate uuid without installing node or python',
    'best free uuid guid generator online tool',
    'uuid generator without signing up or creating account',
  ],
  'password-generator': [
    'password generator online free no signup',
    'strong password generator free no registration',
    'secure random password generator online free',
    'generate strong password for account security',
    'how to generate secure random password online',
    'how to create strong password with special characters',
    'how to make unique password for every account',
    'password generator with custom length and symbols',
    'password generator for website accounts free online',
    'memorable passphrase generator free online tool',
    'best free password generator online no account',
    'password generator without installing password manager',
  ],
  'qr-generator': [
    'qr code generator online free no signup',
    'generate qr code for url free no registration',
    'qr code maker free online no watermark',
    'create qr code for website link free',
    'how to generate qr code for wifi password',
    'how to create qr code with logo embedded',
    'how to make qr code for business card free',
    'qr code generator with logo and custom colors',
    'batch qr code generator from csv file free',
    'qr code generator for vcard contact sharing',
    'best free qr code generator online no account',
    'qr code creator without installing app or software',
  ],
  'barcode-generator': [
    'free online barcode generator no signup required',
    'bulk barcode generator from excel csv free',
    'ean-13 barcode generator free online',
    'upc-a barcode generator online free',
    'code 128 barcode generator free download png svg',
    'how to create barcode for my product free',
    'barcode generator for retail product labels',
    'barcode generator for inventory management free',
    'batch barcode creator from csv file online',
    'barcode label maker print at home free',
    'isbn barcode generator free online no registration',
    'barcode generator high resolution print quality 300 dpi',
  ],
  'color-picker': [
    'color picker online free no signup',
    'hex color picker with rgb and hsl output free',
    'online color picker tool no registration required',
    'color picker for web designers free online',
    'how to pick colors for website design online',
    'how to convert hex color to rgb online',
    'how to check color contrast for accessibility wcag',
    'color picker with wcag contrast checker free',
    'color picker with tailwind css palette generator',
    'color palette generator from single color free',
    'best free online color picker for developers',
    'color picker without installing software browser based',
  ],
  'color-format-converter': [
    'hex to rgb color converter online free',
    'color converter hex rgb hsl online free',
    'cmyk to hex color converter online free',
    'color format converter no signup required',
    'how to convert hex to rgb color online',
    'how to convert rgb to cmyk for print',
    'what is the difference between hex rgb and hsl',
    'color converter with css variable export',
    'color converter with wcag contrast checker',
    'color palette generator from hex code',
    'best free color converter for web designers',
    'color converter with figma color values',
  ],
  'favicon-generator': [
    'favicon generator online free no signup',
    'create favicon from image online free no registration',
    'favicon maker free instant no account required',
    'generate ico png favicon for website free',
    'how to create favicon for website online free',
    'how to generate all favicon sizes from one image',
    'how to make apple touch icon from logo free',
    'favicon generator with all sizes ico png svg',
    'favicon generator with html implementation code',
    'create android chrome icon for web app free',
    'best free favicon generator online for websites',
    'favicon maker without installing image editing software',
  ],
  'gradient-generator': [
    'css gradient generator online free no signup',
    'how to create css gradient background for website',
    'how to make linear gradient css background online',
    'best free css gradient generator online tool',
    'css gradient generator with multiple color stops',
    'css gradient generator with tailwind css export',
    'free linear radial conic css gradient generator',
    'css gradient code generator copy paste instantly',
    'gradient background generator for website free',
    'css gradient generator with svg export online',
    'css gradient generator for ui design backgrounds',
    'css gradient maker online free no login',
  ],
  'json-validator': [
    'json validator online free no signup',
    'validate json online free no registration required',
    'json syntax checker free instant online',
    'check if json is valid online free no account',
    'how to validate json schema online free',
    'how to check json syntax errors online',
    'how to validate json against json schema',
    'json validator with json schema draft 7 support',
    'json validator with detailed error messages online',
    'json validator for api response testing free',
    'best free json validator online with schema support',
    'validate json without installing code editor or tools',
  ],
  'crontab-builder': [
    'crontab builder online free no signup',
    'cron expression builder online free no registration',
    'cron job scheduler generator free instant online',
    'build crontab expression with visual editor free',
    'how to build cron expression for scheduled job',
    'how to parse cron expression to human readable',
    'how to schedule linux cron job expression online',
    'crontab expression builder with next run time preview',
    'cron job expression generator with common presets',
    'crontab parser and validator online free tool',
    'best free crontab builder online no account needed',
    'build cron schedule without remembering cron syntax',
  ],
  'list-compare': [
    'compare two lists online free',
    'compare two lists find differences free',
    'list comparison tool no signup required',
    'compare two lists without excel online',
    'how to compare two lists online',
    'how to find items only in one list',
    'how to find common items between two lists',
    'list comparison tool with venn diagram',
    'compare lists find intersection union difference',
    'compare two lists find duplicates online',
    'best free list diff tool online',
    'list comparison tool for data analysis',
  ],
  'curl-to-code': [
    'curl to code converter online free',
    'convert curl command to python requests',
    'curl to javascript fetch code generator',
    'curl to axios node js converter online',
    'how to convert curl to golang http request',
    'curl to php guzzle code converter free',
    'best free curl to code converter no signup',
    'convert curl command to multiple languages online',
    'curl to python javascript go code generator',
    'curl converter with error handling async await',
    'convert api curl example to production code',
    'browser based curl to code converter private secure',
  ],
  'curl-to-ruby': [
    'convert curl to ruby net http online',
    'curl to httparty code generator',
    'ruby net http from curl command',
    'rails curl to ruby converter',
    'ruby api client from curl',
    'curl to ruby with headers auth body',
    'best free curl to ruby converter',
    'httparty from curl example',
    'convert curl to ruby with error handling',
    'curl to ruby production code',
  ],
  'curl-to-httpie': [
    'convert curl to httpie command online',
    'httpie syntax from curl command',
    'http command short-hand from curl',
    'curl to httpie with headers and auth',
    'curl to httpie json mode',
    'httpie from chrome devtools copy as curl',
    'best free curl to httpie converter',
    'curl to httpie vs wget powershell',
    'convert curl to httpie shell friendly',
    'httpie from curl example',
  ],
  'curl-to-java': [
    'convert curl to java httpclient online',
    'curl to okhttp java code generator',
    'java 11 httpclient from curl command',
    'curl to java with headers auth body',
    'spring boot curl to java converter',
    'java httpclient async post from curl',
    'best free curl to java converter',
    'curl to okhttp3 code generator',
    'convert curl to java with error handling',
    'curl to java production code generator',
  ],
  'curl-to-csharp': [
    'convert curl to c# httpclient online',
    'curl to restsharp code generator',
    'c# httpclient async from curl command',
    'curl to c# with headers auth body',
    'dotnet core curl to c# converter',
    'c# httpclient post from curl',
    'best free curl to c# converter',
    'curl to restsharp code example',
    'convert curl to c# with error handling',
    'curl to c# production code generator',
  ],
  'curl-to-axios': [
    'convert curl to axios request config online',
    'curl to axios typescript async await',
    'javascript axios code from curl command',
    'curl to axios with headers auth data',
    'nodejs axios from curl example',
    'axios post request from curl command',
    'best free curl to axios converter',
    'curl to axios request interceptor setup',
    'axios from chrome devtools copy as curl',
    'curl to axios production code generator',
  ],
  'curl-to-httpx': [
    'convert curl to python httpx async',
    'curl to httpx AsyncClient code generator',
    'python httpx from curl command online',
    'curl to httpx with headers auth json body',
    'async httpx from curl example',
    'httpx post request from curl',
    'python httpx vs requests curl converter',
    'curl to httpx production code',
    'httpx from chrome devtools copy as curl',
    'fastapi httpx client from curl',
  ],
  'curl-to-go': [
    'convert curl to golang net/http online',
    'curl to go resty code generator',
    'golang http client from curl command',
    'curl to go with context and timeout',
    'convert curl to go http.NewRequest',
    'curl to go defer Body.Close pattern',
    'best free curl to go converter',
    'curl command to golang production code',
    'go api client from curl request',
    'curl to golang with headers and auth',
  ],
  'curl-to-php': [
    'convert curl command to php guzzle online',
    'curl to php code generator free no signup',
    'curl to php curl_init example',
    'php http client from curl command',
    'convert curl to php with error handling',
    'curl command to php file_get_contents converter',
    'best free curl to php converter',
    'curl to php guzzle library code generator',
    'php api request generator from curl',
    'curl to php with headers and authentication',
  ],
  'json-to-typescript': [
    'json to typescript converter online free',
    'generate typescript interfaces from json data',
    'json to ts interface generator with nested objects',
    'convert api response to typescript types online',
    'json to typescript with optional properties',
    'how to convert json to typescript automatically',
    'json to zod schema generator online free',
    'best free json to typescript interface generator',
    'json to typescript converter with union types',
    'generate typescript types from json api response',
    'json to typescript with enum detection and readonly',
    'convert json schema to typescript interfaces online',
  ],
  'css-minifier': [
    'css minifier online free no signup',
    'how to minify css file for production website',
    'free online css minifier compressor tool',
    'how to minify css for faster website performance',
    'minify css to improve page load speed online',
    'css minifier and beautifier online free',
    'how to reduce css file size without breaking styles',
    'css minifier with vendor prefix and media query optimization',
    'best free css minifier online no registration',
    'minify css for google pagespeed insights online',
    'css minifier beautifier with color compression',
    'compress css stylesheet online free instant',
  ],
  'css-box-shadow-generator': [
    'css box shadow generator online free',
    'box shadow css generator with preview',
    'how to add box shadow in css',
    'css multiple box shadow generator',
    'css box shadow generator with live preview',
    'how to create inset box shadow in css',
    'css layered box shadow generator with presets',
    'box shadow generator with color and opacity',
    'css box shadow code generator copy paste',
    'box shadow generator vs cssmatic online tool',
    'free box shadow generator no signup like getcssscan',
    'how to make soft drop shadow css for cards',
  ],
  'js-minifier': [
    'javascript minifier online free',
    'minify javascript online free no signup',
    'javascript minifier and beautifier online',
    'compress javascript code online free',
    'how to minify javascript online',
    'how to reduce javascript bundle size online',
    'minify javascript code to improve website speed',
    'javascript minifier with es6 es2024 support',
    'javascript minifier with source maps online',
    'minify javascript for production bundle optimization',
    'best free javascript minifier tool online',
    'uglify js alternative online free',
  ],
  'yaml-json-converter': [
    'yaml to json converter online free',
    'json to yaml converter online free',
    'yaml to json converter no signup required',
    'convert yaml to json in browser instantly',
    'how to convert yaml to json online',
    'convert yaml to json without installing software',
    'how to convert kubernetes yaml to json',
    'yaml to json converter for kubernetes manifests',
    'yaml to json converter for docker compose files',
    'bidirectional yaml json converter online',
    'best free yaml to json converter online',
    'yaml to json converter with syntax validation',
  ],
  'yaml-validator': [
    'yaml validator online free no signup',
    'how to validate yaml file syntax online',
    'free yaml syntax checker no registration required',
    'yaml validator for kubernetes manifests online',
    'how to check yaml syntax errors with line numbers',
    'yaml validator for docker compose and github actions',
    'best free yaml validator online tool',
    'yaml lint checker online free instant results',
    'validate yaml kubernetes manifest before deployment',
    'yaml syntax checker for ansible and helm charts',
    'yaml validator with duplicate key detection online',
    'check yaml file for errors without installing software',
  ],
  'unix-timestamp-converter': [
    'unix timestamp converter online free no signup',
    'how to convert unix timestamp to date online',
    'epoch to date converter with timezone support',
    'convert epoch time to human readable date free',
    'unix timestamp to date converter milliseconds seconds',
    'convert unix timestamp to date javascript python',
    'best free epoch unix timestamp converter online',
    'epoch time to date converter no registration',
    'unix timestamp converter for api debugging online',
    'convert epoch to iso 8601 date format online',
    'current unix timestamp to human readable date',
    'unix epoch time converter without signup instant',
  ],
  'eml-to-html': [
    'eml to html converter online free',
    'convert eml file to html no signup required',
    'open eml file online without outlook free',
    'eml viewer online free no registration',
    'how to convert eml email file to html',
    'how to open eml file without email client',
    'how to view eml file in browser online',
    'eml to html converter with attachment extraction',
    'eml file viewer with header parsing online',
    'convert outlook email eml file to html free',
    'best free eml to html converter online tool',
    'eml converter without installing email software',
  ],
  'ai-prompt-token-counter': [
    'ai token counter online free no signup',
    'count tokens for openai gpt-4 api calls',
    'how to count tokens before sending api request',
    'openai api cost calculator token pricing estimator',
    'claude token counter with cost estimation',
    'gpt-4 token counter and context window checker',
    'llm token calculator compare models pricing',
    'free tiktoken alternative online token counter',
    'prompt token counter for chatgpt claude gemini',
    'optimize prompt to reduce tokens and api costs',
    'ai api cost estimator multiple models comparison',
    'count tokens for prompt engineering and optimization',
  ],
  'pdf-to-word': [
    'pdf to word converter online free',
    'convert pdf to docx no signup required',
    'pdf to word converter free no watermark',
    'convert pdf to editable word document online free',
    'how to convert pdf to word without losing formatting',
    'how to convert pdf to word document online',
    'how to edit pdf by converting to word free',
    'pdf to word converter preserve formatting free',
    'pdf to docx converter with image extraction',
    'batch pdf to word converter online free',
    'best free pdf to word converter online tool',
    'convert pdf to word without adobe acrobat',
  ],
  'image-to-pdf': [
    'image to pdf converter online free no signup',
    'how to combine multiple images into one pdf',
    'convert jpg png to pdf free no upload required',
    'merge multiple photos into one pdf document free',
    'jpg to pdf converter online free no watermark',
    'image to pdf converter with custom page size margins',
    'how to turn multiple pictures into a pdf file',
    'convert images to pdf without installing software',
    'combine jpg png webp images into pdf online',
    'image to pdf converter for scanned documents online',
    'best free image to pdf converter online tool',
    'convert multiple photos to pdf a4 letter format',
  ],
  'jpg-to-pdf': [
    'convert jpg to pdf online free',
    'jpg to pdf converter without losing quality',
    'combine multiple jpg images into one pdf',
    'jpg to pdf converter no watermark free',
    'how to convert jpeg to pdf without software',
    'free online jpg to pdf no download required',
    'batch convert jpg to pdf online free',
    'jpg to pdf with custom page size options',
    'convert jpeg photos to pdf document free',
    'jpg to pdf no signup no registration needed',
    'merge jpg files into single pdf online',
    'secure browser based jpg to pdf converter',
  ],
  'png-to-pdf': [
    'convert png to pdf online free',
    'png to pdf converter without losing quality',
    'combine multiple png images into one pdf',
    'png to pdf converter no watermark free',
    'how to convert png to pdf with transparency',
    'free online png to pdf no download required',
    'batch convert png to pdf online free',
    'png to pdf preserve transparent background',
    'merge png files into single pdf document',
    'png to pdf no signup no registration needed',
    'convert png screenshots to pdf document free',
    'secure browser based png to pdf converter',
  ],
  'gif-to-pdf': [
    'gif to pdf converter online free',
    'convert gif to pdf online no signup',
    'batch convert gif to pdf online free',
    'animated gif to pdf converter online free',
    'how to convert gif to pdf online',
    'how to turn gif images into pdf document',
    'how to convert animated gif to pdf free',
    'gif to pdf converter custom page size a4',
    'convert multiple gif files to one pdf',
    'gif to pdf converter with no file upload',
    'best free gif to pdf converter no watermark',
    'gif to pdf converter without adobe acrobat',
  ],
  'whatsapp-link-generator': [
    'whatsapp link generator online free',
    'create whatsapp click to chat link',
    'how to create wa.me link with message',
    'free whatsapp qr code generator with message',
    'whatsapp chat link generator with pre-filled message',
    'whatsapp link generator no registration required',
    'create whatsapp button for website free',
    'whatsapp direct message link without saving number',
    'whatsapp link for business card qr code',
    'how to make whatsapp link for website',
    'whatsapp short link generator for social media',
    'free whatsapp link creator with qr code',
  ],
  'utm-builder': [
    'utm builder online free no signup',
    'google analytics campaign url builder free',
    'how to create utm parameters for tracking',
    'utm tag generator for social media campaigns',
    'utm link builder with saved templates',
    'bulk utm url generator for marketing teams',
    'free utm code generator for email campaigns',
    'utm builder for google analytics ga4',
    'create trackable links for social media ads',
    'campaign url builder with naming conventions',
    'utm parameter generator with presets and export',
    'best free utm builder alternative to google',
  ],
  'youtube-timestamp-generator': [
    'youtube timestamp generator online free',
    'how to add chapters to youtube video description',
    'youtube chapter generator free no signup',
    'create clickable timestamp links for youtube',
    'youtube timestamp link generator share video moment',
    'how to create youtube chapters for seo',
    'generate youtube video timestamps with labels',
    'youtube chapters format copy paste description',
    'free tool to make youtube video chapters',
    'youtube timestamp generator for podcast episodes',
    'create youtube chapters for long videos tutorials',
    'youtube video chapter maker with time converter',
  ],
  'chmod-calculator': [
    'chmod calculator online free no signup',
    'linux file permissions calculator free online',
    'convert chmod octal to symbolic notation online',
    'chmod 755 644 777 permissions calculator free',
    'how to calculate chmod permissions online',
    'how to set linux file permissions using chmod',
    'how to convert octal to rwx permissions online',
    'chmod calculator with recursive flag option',
    'unix file permissions calculator with visual grid',
    'chmod permission calculator for web server files',
    'best free chmod calculator online no registration',
    'chmod calculator without installing linux terminal',
  ],
  'htaccess-generator': [
    'htaccess generator online free no login required',
    'how to create htaccess file for apache redirects',
    'how to force https redirect in htaccess file',
    'free htaccess generator for apache redirects',
    'htaccess 301 redirect generator without coding',
    'how to set up 301 redirects in htaccess file',
    'htaccess generator with wordpress security rules',
    'best free htaccess generator online tool',
    'generate htaccess file without writing code',
    'htaccess redirect generator for website migration',
    'htaccess generator with gzip compression and caching',
    'htaccess generator for beginners no coding required',
  ],
  'lorem-ipsum-generator': [
    'lorem ipsum generator online free',
    'generate lorem ipsum paragraphs',
    'lorem ipsum copy paste',
    'placeholder text generator for designers',
    'dummy text generator for website mockup',
    'how to generate lorem ipsum text',
    'lorem ipsum generator with word count',
    'custom lorem ipsum paragraph generator',
    'free online placeholder text generator',
    'lorem ipsum sentences generator no signup',
    'generate dummy text for web design',
    'lipsum generator with custom length',
  ],
  'string-case-converter': [
    'string case converter online free no signup',
    'convert camelcase to snake case online free',
    'convert snake case to camelcase online free',
    'how to convert text to camelcase online',
    'how to convert variable names between cases online',
    'how to change camelcase to kebab case online',
    'camelcase to snake case converter for developers',
    'string case converter with batch conversion mode',
    'convert text case for code refactoring online free',
    'text case converter for javascript python naming',
    'best free string case converter for developers',
    'convert naming convention without writing code',
  ],
  'binary-to-text': [
    'binary to text converter online free no signup',
    'convert binary to text online free no registration',
    'decode binary code to ascii text online free',
    'convert text to binary numbers online free',
    'how to convert binary to readable text online',
    'how to decode binary code from network packets',
    'how to convert ascii text to binary online free',
    'binary to text converter with utf-8 support',
    'text to binary encoder with hex conversion free',
    'binary code translator for computer science learning',
    'best free binary to text converter online tool',
    'binary decoder without installing programming environment',
  ],
  'js-object-to-json': [
    'javascript object to json converter online free',
    'convert js object to json online free no signup',
    'js object literal to json converter no registration',
    'convert javascript object to valid json free online',
    'how to convert javascript object to json online',
    'how to stringify javascript object with special values',
    'how to handle circular references in json conversion',
    'js object to json converter with bigint support',
    'convert devtools copied object to valid json free',
    'javascript to json with function and undefined handling',
    'best free javascript object to json converter online',
    'convert js object to json without running node.js',
  ],
  'html-to-markdown': [
    'html to markdown converter online free no signup',
    'convert html to markdown no registration required',
    'html to markdown converter free instant online',
    'paste html and get markdown free online tool',
    'how to convert html to markdown online',
    'how to convert wordpress html to markdown',
    'how to turn html into clean markdown for github',
    'html to markdown with github flavored markdown support',
    'html to markdown converter for notion and obsidian',
    'convert wysiwyg html output to markdown online',
    'best free html to markdown converter online',
    'html to markdown without installing node packages',
  ],
  'pdf-to-jpg': [
    'pdf to jpg converter online free no signup',
    'convert pdf to png online free',
    'extract images from a pdf online',
    'best free pdf to jpg converter online',
    'how to convert pdf to image',
    'how to convert pdf pages into images',
    'how to convert pdf to high resolution jpg',
    'convert pdf to jpg high quality',
    'convert all pages in a pdf to jpg',
    'convert pdf to webp images online',
    'pdf to jpg converter no upload private',
    'convert pdf to image without watermark',
  ],
  'merge-pdf': [
    'merge pdf online free',
    'combine pdf files into one',
    'join pdf files online',
    'merge pdf no signup no watermark',
    'how to merge pdf files',
    'how to combine multiple pdfs into one document',
    'how to merge pdf without adobe acrobat',
    'merge pdf files and reorder pages',
    'combine pdf files in your browser',
    'merge pdf without uploading files',
    'best free pdf merger online',
    'merge pdf without file size limit',
  ],
  'split-pdf': [
    'split pdf online free',
    'extract pages from pdf',
    'split pdf into separate files',
    'split pdf no signup no watermark',
    'how to split a pdf',
    'how to split a pdf into multiple files',
    'how to extract specific pages from a pdf',
    'split pdf by clicking between pages',
    'split pdf into one file per page',
    'split pdf with custom page ranges',
    'best free pdf splitter online',
    'split pdf without uploading files',
  ],
  'image-resizer': [
    'resize image online free no signup',
    'resize image in pixels online free',
    'resize photo without losing quality online',
    'bulk resize images online free',
    'how to resize an image without losing quality',
    'how to resize an image in pixels',
    'how to resize photo by percentage',
    'resize image with aspect ratio locked',
    'resize image by percentage online',
    'resize image to png jpg or webp',
    'best free image resizer online',
    'browser image resizer vs online upload tools',
  ],
  'image-compressor': [
    'compress image online free no signup',
    'reduce image file size online free',
    'compress jpg online without losing quality',
    'compress png and webp images online',
    'how to reduce image file size without losing quality',
    'how to compress an image for web',
    'how to compress jpg to smaller size',
    'compress image with quality slider',
    'compress image in the browser privately',
    'convert png to webp while compressing',
    'best free image compressor online',
    'image compressor vs tinypng no upload',
  ],
};

/**
 * Get long-tail keywords for a tool.
 * Returns empty array if tool has no entries (safe to spread).
 */
export function getToolLongTailKeywords(toolId: string): string[] {
  return toolLongTailKeywords[toolId] ?? [];
}
