export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  categories: string[]; // Array of category IDs from categories: Category[]
  keywords: string[];
  isNew?: boolean;
  searchVolume: number;
  label?: 'popular' | 'new' | 'coming-soon' | 'test' | ''; // Tool label for badges
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
  tools: Tool[];
}

// Tool data
export const tools: Tool[] = [
  // Data & Conversion Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description:
      'Format, validate and beautify JSON data with syntax highlighting',
    icon: '📋',
    route: '/tools/json-formatter',
    categories: ['data', 'formatters'],
    keywords: ['json', 'format', 'validate', 'prettify', 'parse'],
    searchVolume: 400000,
    label: '',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV files to JSON format with customizable options',
    icon: '🔄',
    route: '/tools/csv-to-json',
    categories: ['data'],
    keywords: [
      'csv',
      'json',
      'convert',
      'data',
      'transform',
      'spreadsheet',
      'excel',
    ],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description:
      'Convert JSON to CSV with advanced formatting, flattening, and column mapping options',
    icon: '📊',
    route: '/tools/json-to-csv',
    categories: ['data', 'dev'],
    keywords: [
      'json to csv',
      'json converter',
      'convert json to excel',
      'json to csv online',
      'json parser',
      'json',
      'csv',
      'excel',
      'spreadsheet',
      'export',
      'data transformation',
      'flatten json',
      'json array',
      'tabular data',
    ],
    searchVolume: 32000,
    label: '',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation',
    icon: '🗃️',
    route: '/tools/sql-formatter',
    categories: ['formatters', 'data', 'text'],
    keywords: ['sql', 'format', 'database', 'query', 'beautify'],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description:
      'Format, validate, and minify XML documents with syntax highlighting and XPath support',
    icon: '📄',
    route: '/tools/xml-formatter',
    categories: ['formatters', 'data'],
    keywords: [
      'xml',
      'formatter',
      'beautify',
      'minify',
      'validate',
      'parser',
      'xpath',
      'namespace',
      'schema',
      'soap',
      'rss',
      'svg',
      'markup',
      'xsd',
      'dtd',
    ],
    searchVolume: 40000,
    label: '',
  },
  {
    id: 'xml-to-json-converter',
    name: 'XML to JSON Converter',
    description:
      'Convert XML documents to JSON format with attribute handling, namespace support, and smart array detection',
    icon: '🔄',
    route: '/tools/xml-to-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'xml to json',
      'xml converter',
      'convert xml to json',
      'xml parser',
      'xml',
      'json',
      'converter',
      'parser',
      'namespace',
      'attributes',
      'cdata',
      'soap to json',
      'rss to json',
      'api',
      'data transformation',
    ],
    searchVolume: 12000,
    label: '',
  },

  // Encoding & Security Tools
  {
    id: 'base64-encode',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with file support',
    icon: '🔐',
    route: '/tools/base64-encode',
    categories: ['encoding', 'base64'],
    keywords: ['base64', 'encode', 'decode', 'encryption', 'security'],
    searchVolume: 150000,
    label: '',
  },
  {
    id: 'url-encode',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components and query parameters',
    icon: '🔗',
    route: '/tools/url-encode',
    categories: ['encoding'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    searchVolume: 50000,
    label: '',
  },
  {
    id: 'html-encode-decode',
    name: 'HTML Encoder/Decoder',
    description:
      'Convert text to HTML entities and decode HTML entities to plain text',
    icon: '🏷️',
    route: '/tools/html-encode-decode',
    categories: ['encoding', 'text'],
    keywords: [
      'html',
      'encode',
      'decode',
      'entities',
      'escape',
      'unescape',
      'sanitize',
      'xss',
      'special characters',
      'xml',
    ],
    isNew: true,
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-256, SHA-512 hashes and HMAC signatures — with file hashing, bulk mode, and hash comparison',
    icon: '#️⃣',
    route: '/tools/hash-generator',
    categories: ['encoding'],
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'hmac', 'checksum', 'file hash', 'hash compare', 'crc32'],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Encoder/Decoder',
    description: 'Decode, verify, encode and sign JSON Web Tokens — all in your browser',
    icon: '🎫',
    route: '/tools/jwt-decoder',
    categories: ['encoding'],
    keywords: ['jwt', 'json', 'web', 'token', 'decode', 'encode', 'sign', 'verify', 'create', 'generator', 'signer', 'encoder', 'signature', 'expiration', 'validate', 'hs256', 'rs256', 'es256'],
    isNew: true,
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'bcrypt-hash-generator',
    name: 'Bcrypt Hash Generator',
    description:
      'Generate and verify bcrypt password hashes with configurable cost factor for secure password storage',
    icon: '🔒',
    route: '/tools/bcrypt-hash-generator',
    categories: ['encoding', 'dev'],
    keywords: [
      'bcrypt',
      'hash',
      'password',
      'generator',
      'verify',
      'security',
      'encryption',
      'salt',
      'rounds',
      'cost factor',
    ],
    searchVolume: 5000,
    label: '',
  },
  {
    id: 'rot13-caesar-cipher',
    name: 'ROT13 / Caesar Cipher',
    description:
      'Encode and decode text with ROT13 or any Caesar shift from 1 to 25',
    icon: '🔄',
    route: '/tools/rot13-caesar-cipher',
    categories: ['encoding'],
    keywords: [
      'rot13',
      'caesar',
      'cipher',
      'encode',
      'decode',
      'shift',
      'rotation',
      'classical',
      'cryptography',
      'ctf',
      'spoiler',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'base64-to-pdf',
    name: 'Base64 to PDF',
    description: 'Convert Base64 encoded data to PDF files and download them',
    icon: '📄',
    route: '/tools/base64-to-pdf',
    categories: ['base64', 'data', 'pdf'],
    keywords: [
      'base64',
      'pdf',
      'convert',
      'download',
      'decode',
      'file',
      'document',
      'viewer',
      'preview',
      'base64 to pdf',
      'base64 decode pdf',
      'base64 string',
      'pdf converter',
      'online',
      'free',
    ],
    searchVolume: 7000,
    label: 'popular',
  },
  {
    id: 'base64-to-gif',
    name: 'Base64 to GIF',
    description:
      'Convert Base64 encoded data to GIF images and download them with preview',
    icon: '🎞️',
    route: '/tools/base64-to-gif',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'gif',
      'image',
      'convert',
      'download',
      'decode',
      'animation',
    ],
    searchVolume: 1800,
    label: '',
  },
  {
    id: 'base64-to-png',
    name: 'Base64 to PNG',
    description:
      'Convert Base64 encoded data to PNG images with instant preview and download',
    icon: '🖼️',
    route: '/tools/base64-to-png',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'png',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    searchVolume: 3800,
    label: '',
  },
  {
    id: 'base64-to-jpg',
    name: 'Base64 to JPG',
    description:
      'Convert Base64 encoded data to JPG/JPEG images with instant preview and download',
    icon: '📸',
    route: '/tools/base64-to-jpg',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'jpg',
      'jpeg',
      'image',
      'convert',
      'download',
      'decode',
      'picture',
      'photo',
    ],
    searchVolume: 4500,
    label: '',
  },
  {
    id: 'base64-to-webp',
    name: 'Base64 to WebP',
    description:
      'Convert Base64 encoded data to WebP images with instant preview, transparency support and compression info',
    icon: '⚡',
    route: '/tools/base64-to-webp',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'webp',
      'image',
      'convert',
      'download',
      'decode',
      'modern',
      'compression',
      'lossy',
      'lossless',
    ],
    searchVolume: 2200,
    label: '',
  },
  {
    id: 'excel-filter',
    name: 'Excel Filter Tool',
    description:
      'Upload Excel files and apply dynamic filters to tables with search, sort, and export capabilities',
    icon: '📊',
    route: '/tools/excel-filter',
    categories: ['data'],
    keywords: [
      'excel',
      'filter',
      'spreadsheet',
      'table',
      'data',
      'search',
      'sort',
      'export',
      'csv',
      'xlsx',
      'query',
      'analyze',
      'viewer',
      'browser',
      'online',
    ],
    searchVolume: 8000,
    label: '',
  },

  // Text & Format Tools
  {
    id: 'instagram-font-generator',
    name: 'Instagram Font Generator',
    description:
      'Generate stylized Unicode fonts for Instagram, WhatsApp, and social media bios',
    icon: '✨',
    route: '/tools/instagram-font-generator',
    categories: ['social', 'text'],
    keywords: [
      'instagram',
      'font',
      'generator',
      'unicode',
      'text',
      'style',
      'fancy',
      'bio',
      'whatsapp',
      'social',
      'media',
      'bold',
      'italic',
      'cursive',
      'monospace',
      'aesthetic',
      'fonts for instagram',
      'instagram bio fonts',
      'fancy text generator',
      'unicode text',
      'stylish text',
      'cool fonts',
      'text decorator',
    ],
    searchVolume: 95000,
    label: '',
  },
  {
    id: 'linkedin-post-formatter',
    name: 'LinkedIn Post Formatter',
    description:
      'Format LinkedIn posts with bold, italic, and special characters using Unicode. Increase engagement with professional formatting.',
    icon: '💼',
    route: '/tools/linkedin-post-formatter',
    categories: ['social', 'text'],
    keywords: [
      'linkedin',
      'post',
      'formatter',
      'bold',
      'italic',
      'unicode',
      'text',
      'formatting',
      'social',
      'media',
      'professional',
      'engagement',
      'bullet',
      'points',
      'linkedin post',
      'linkedin formatting',
      'linkedin bold text',
    ],
    searchVolume: 5000,
    label: '',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description:
      'Compare files and code with advanced diff features and syntax highlighting',
    icon: '📝',
    route: '/tools/text-diff',
    categories: ['text', 'dev'],
    keywords: [
      'diff',
      'compare',
      'text',
      'difference',
      'merge',
      'patch',
      'git',
      'code',
      'file',
    ],
    searchVolume: 60000,
    label: '',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description:
      'Edit and preview Markdown with live rendering, export to HTML/PDF, and comprehensive statistics',
    icon: '📖',
    route: '/tools/markdown-preview',
    categories: ['text', 'formatters'],
    keywords: [
      'markdown',
      'preview',
      'html',
      'convert',
      'format',
      'editor',
      'gfm',
      'github',
      'export',
      'pdf',
    ],
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with live matching',
    icon: '🔍',
    route: '/tools/regex-tester',
    categories: ['text'],
    keywords: ['regex', 'regexp', 'pattern', 'test', 'match'],
    searchVolume: 39000,
    label: '',
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID/GUID in various formats (v1, v4, etc.)',
    icon: '🆔',
    route: '/tools/uuid-generator',
    categories: ['generators'],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    searchVolume: 100000,
    label: '',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords with customizable options',
    icon: '🔑',
    route: '/tools/password-generator',
    categories: ['generators'],
    keywords: ['password', 'generate', 'secure', 'random', 'strong'],
    searchVolume: 350000,
    label: '',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description:
      'Generate QR codes with advanced customization, logos, batch processing and developer tools',
    icon: '📱',
    route: '/tools/qr-generator',
    categories: ['generators', 'dev', 'web'],
    keywords: [
      'qr',
      'code',
      'generate',
      'barcode',
      'scan',
      'wifi',
      'vcard',
      'batch',
      'svg',
      'logo',
      'api',
      'developer',
    ],
    searchVolume: 550000,
    label: '',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description:
      'Generate all types of barcodes - EAN, UPC, Code 128, QR codes, Data Matrix and more with customization',
    icon: '📊',
    route: '/tools/barcode-generator',
    categories: ['generators', 'dev'],
    keywords: [
      'barcode',
      'generator',
      'ean',
      'upc',
      'code 128',
      'code 39',
      'qr code',
      'data matrix',
      'isbn',
      'retail',
      'product',
      'inventory',
      'shipping',
      'warehouse',
      'label',
      'scanner',
      'batch',
      'svg',
      'png',
      'pdf',
    ],
    searchVolume: 350000,
    label: '',
  },

  // Web & Design Tools
  {
    id: 'color-picker',
    name: 'Color Picker',
    description:
      'Professional color picker with palettes, contrast checker and format conversion',
    icon: '🎨',
    route: '/tools/color-picker',
    categories: ['web', 'dev'],
    keywords: [
      'color',
      'picker',
      'hex',
      'rgb',
      'hsl',
      'hsv',
      'cmyk',
      'palette',
      'generator',
      'contrast',
      'checker',
      'wcag',
      'accessibility',
      'css',
      'tailwind',
      'material',
      'design',
      'eyedropper',
      'gradient',
      'harmony',
      'complementary',
      'triadic',
      'analogous',
      'color blindness',
      'lab',
      'pantone',
    ],
    searchVolume: 350000,
    label: '',
  },
  {
    id: 'color-format-converter',
    name: 'Color Format Converter',
    description:
      'Convert colors between HEX, RGB, HSL, HSV, and CMYK formats with palette generation and contrast checker',
    icon: '🌈',
    route: '/tools/color-format-converter',
    categories: ['web', 'generators', 'dev'],
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'hsl to hex',
      'hsv to rgb',
      'cmyk converter',
      'color format',
      'hex converter',
      'rgb converter',
      'color code',
      'color transformation',
      'color palette generator',
      'color shades',
      'color tints',
      'wcag contrast',
      'accessibility',
      'css colors',
      'color picker',
      'web colors',
      'design colors',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description:
      'Resize images by pixels, percentage or to fit — fast and private in your browser',
    icon: '🖼️',
    route: '/tools/image-resizer',
    categories: ['web'],
    keywords: [
      'image resizer',
      'resize image',
      'resize image online',
      'resize photo',
      'change image dimensions',
      'scale image',
      'resize jpg',
      'resize png',
      'image resize tool',
      'resize image in pixels',
      'resize image by percentage',
      'bulk image resize',
    ],
    searchVolume: 450000,
    label: '',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description:
      'Compress JPG, PNG and WebP images to reduce file size without visible quality loss',
    icon: '🗜️',
    route: '/tools/image-compressor',
    categories: ['web'],
    keywords: [
      'image compressor',
      'compress image',
      'compress image online',
      'reduce image size',
      'image optimizer',
      'optimize image',
      'compress jpg',
      'compress png',
      'shrink image',
      'reduce photo size',
      'compress image to kb',
      'image size reducer',
    ],
    searchVolume: 150000,
    label: '',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description:
      'Convert iPhone HEIC/HEIF photos to JPG or PNG right in your browser — no upload',
    icon: '📸',
    route: '/tools/heic-to-jpg',
    categories: ['web'],
    keywords: [
      'heic to jpg',
      'heic to jpeg',
      'heic to png',
      'convert heic',
      'heic converter',
      'iphone photo converter',
      'heif to jpg',
      'change heic to jpg',
      'open heic file',
      'heic to jpg online',
      'apple photo format converter',
    ],
    searchVolume: 200000,
    label: '',
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    description:
      'Convert times between timezones and plan meetings across the world at a glance',
    icon: '🌍',
    route: '/tools/timezone-converter',
    categories: ['data', 'dev'],
    keywords: [
      'timezone converter',
      'time zone converter',
      'time converter',
      'world clock',
      'meeting planner',
      'utc converter',
      'gmt converter',
      'est to pst',
      'convert time between timezones',
      'time difference calculator',
      'schedule across timezones',
    ],
    searchVolume: 60000,
    label: '',
  },
  {
    id: 'json-repair',
    name: 'JSON Repair',
    description:
      'Fix broken or malformed JSON — trailing commas, single quotes, missing brackets and LLM output',
    icon: '🩹',
    route: '/tools/json-repair',
    categories: ['data', 'formatters'],
    keywords: [
      'json repair',
      'fix json',
      'json fixer',
      'repair json online',
      'fix broken json',
      'json error fix',
      'malformed json',
      'fix invalid json',
      'clean json',
      'fix json from chatgpt',
      'json syntax fixer',
    ],
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description:
      'Minify and clean SVG files — strip editor cruft, comments and metadata to shrink file size',
    icon: '🧹',
    route: '/tools/svg-optimizer',
    categories: ['web'],
    keywords: [
      'svg optimizer',
      'svg minifier',
      'minify svg',
      'optimize svg',
      'compress svg',
      'svgo online',
      'clean svg',
      'reduce svg size',
      'svg cleaner',
      'shrink svg file',
      'svg optimization tool',
    ],
    searchVolume: 40000,
    label: '',
  },
  {
    id: 'exif-viewer',
    name: 'EXIF Viewer & Remover',
    description:
      'View photo EXIF metadata (camera, GPS, date) and strip it to protect your privacy',
    icon: '🔍',
    route: '/tools/exif-viewer',
    categories: ['web'],
    keywords: [
      'exif viewer',
      'exif remover',
      'view exif data',
      'remove exif data',
      'photo metadata viewer',
      'strip exif',
      'remove gps from photo',
      'image metadata remover',
      'check photo location data',
      'exif data online',
      'clear image metadata',
    ],
    searchVolume: 25000,
    label: '',
  },
  {
    id: 'env-to-json',
    name: '.env to JSON',
    description:
      'Convert .env files to JSON and back — parse environment variables both ways',
    icon: '🔧',
    route: '/tools/env-to-json',
    categories: ['dev', 'data'],
    keywords: [
      'env to json',
      'json to env',
      'dotenv to json',
      'convert env file',
      'env file parser',
      'environment variables to json',
      'parse dotenv',
      'env converter',
      'dotenv json converter',
      '.env to json online',
      'env file to json',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'llms-txt-generator',
    name: 'llms.txt Generator',
    description:
      'Generate an llms.txt file to guide AI crawlers like ChatGPT and Claude to your key content',
    icon: '🤖',
    route: '/tools/llms-txt-generator',
    categories: ['web', 'generators'],
    keywords: [
      'llms.txt generator',
      'llms txt',
      'generate llms.txt',
      'llms.txt file',
      'ai crawler file',
      'llms txt standard',
      'llm txt generator',
      'ai seo file',
      'llms.txt example',
      'create llms.txt',
      'llms full txt',
    ],
    searchVolume: 8000,
    label: '',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description:
      'Generate complete favicon packages with all sizes and formats',
    icon: '🖥️',
    route: '/tools/favicon-generator',
    categories: ['web', 'generators'],
    keywords: [
      'favicon',
      'icon',
      'apple-touch-icon',
      'android-chrome',
      'website-icon',
      'ico',
      'png',
      'image',
    ],
    isNew: true,
    searchVolume: 32000,
    label: '',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description:
      'Create beautiful CSS gradients with visual editor, presets and real-time preview',
    icon: '🌈',
    route: '/tools/gradient-generator',
    categories: ['web', 'generators'],
    keywords: [
      'gradient',
      'css',
      'linear',
      'radial',
      'conic',
      'color',
      'background',
      'design',
      'web',
      'ui',
      'tailwind',
      'svg',
      'maker',
      'tool',
      'generator',
    ],
    searchVolume: 40000,
    label: '',
  },
  {
    id: 'css-box-shadow-generator',
    name: 'CSS Box Shadow Generator',
    description:
      'Design CSS box-shadow with live preview and sliders for offset, blur, spread, color and opacity',
    icon: '🔲',
    route: '/tools/css-box-shadow-generator',
    categories: ['web', 'generators'],
    keywords: [
      'css box shadow generator',
      'box shadow css',
      'shadow generator online',
      'css shadow tool',
      'box-shadow',
      'css shadow generator',
      'drop shadow css',
      'inset shadow',
      'multiple box shadow',
      'box shadow preview',
      'css',
      'web design',
      'ui',
      'generator',
    ],
    searchVolume: 60000,
    label: '',
  },

  // Dev Utilities
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description:
      'Advanced JSON validation with schema support, error reporting, and security checks',
    icon: '✅',
    route: '/tools/json-validator',
    categories: ['dev', 'data'],
    keywords: [
      'json',
      'validator',
      'schema',
      'validate',
      'check',
      'format',
      'jsonschema',
      'draft',
      'parser',
      'syntax',
      'error',
      'linter',
      'api',
      'development',
      'security',
      'audit',
      'compliance',
      'structure',
      'verification',
      'testing',
    ],
    searchVolume: 90000,
    label: '',
  },
  {
    id: 'crontab-builder',
    name: 'Crontab Expression Builder',
    description:
      'Parse, build, and validate cron expressions with visual builder, presets, and next execution times',
    icon: '⏰',
    route: '/tools/crontab-builder',
    categories: ['dev'],
    keywords: [
      'crontab',
      'cron',
      'scheduler',
      'unix',
      'linux',
      'automation',
      'parser',
      'builder',
      'expression',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'list-compare',
    name: 'List Compare & Diff Tool',
    description:
      'Advanced list comparison with set operations, fuzzy matching, and developer-friendly output formats',
    icon: '📋',
    route: '/tools/list-compare',
    categories: ['dev', 'text'],
    keywords: [
      'list compare',
      'diff lists',
      'set operations',
      'compare arrays',
      'list difference',
      'intersection',
      'union',
      'venn diagram',
      'array diff',
      'list merger',
      'duplicate finder',
      'fuzzy matching',
      'string comparison',
      'data analysis',
      'csv compare',
      'json compare',
      'package dependencies',
      'git files',
      'code compare',
    ],
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description:
      'Convert cURL commands to production-ready code in any programming language with error handling and type safety',
    icon: '🔄',
    route: '/tools/curl-to-code',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to code',
      'curl converter',
      'curl to javascript',
      'curl to python',
      'http client generator',
      'api code generator',
      'curl to axios',
      'curl to fetch',
      'curl to golang',
      'curl to java',
      'curl to csharp',
      'curl to php',
      'curl to ruby',
      'rest api converter',
      'http request converter',
      'postman to code',
      'har to code',
      'api client generator',
      'sdk generator',
    ],
    searchVolume: 10000,
    label: '',
  },
  {
    id: 'curl-to-ruby',
    name: 'cURL to Ruby Converter',
    description:
      'Convert cURL commands to Ruby code using Net::HTTP (stdlib) or HTTParty gem',
    icon: '💎',
    route: '/tools/curl-to-ruby',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to ruby',
      'curl to net http ruby',
      'curl to httparty',
      'ruby http client generator',
      'ruby api request',
      'rails curl converter',
      'curl to ruby online',
    ],
    searchVolume: 6000,
    label: '',
  },
  {
    id: 'curl-to-httpie',
    name: 'cURL to HTTPie Converter',
    description:
      'Convert cURL commands to HTTPie http / https CLI syntax with JSON mode and short-hand flags',
    icon: '🌐',
    route: '/tools/curl-to-httpie',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to httpie',
      'httpie from curl',
      'http command from curl',
      'httpie cli generator',
      'curl to https cli',
      'httpie syntax converter',
      'curl to httpie online',
    ],
    searchVolume: 5000,
    label: '',
  },
  {
    id: 'curl-to-java',
    name: 'cURL to Java Converter',
    description:
      'Convert cURL commands to Java code using HttpClient (Java 11+) or OkHttp client',
    icon: '☕',
    route: '/tools/curl-to-java',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to java',
      'curl to httpclient',
      'curl to okhttp',
      'java http client generator',
      'java api request',
      'java curl example',
      'java httpclient from curl',
      'curl to java online',
    ],
    searchVolume: 14000,
    label: '',
  },
  {
    id: 'curl-to-csharp',
    name: 'cURL to C# Converter',
    description:
      'Convert cURL commands to C# code using HttpClient (async/await) or RestSharp',
    icon: '🎯',
    route: '/tools/curl-to-csharp',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to csharp',
      'curl to c sharp',
      'curl to httpclient c#',
      'curl to restsharp',
      'csharp http client generator',
      'dotnet curl converter',
      'c# api request',
      'curl to c# online',
    ],
    searchVolume: 9000,
    label: '',
  },
  {
    id: 'curl-to-axios',
    name: 'cURL to Axios Converter',
    description:
      'Convert cURL commands to JavaScript axios HTTP client code with interceptors, async/await, and TypeScript support',
    icon: '⚡',
    route: '/tools/curl-to-axios',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to axios',
      'axios from curl',
      'axios generator',
      'javascript axios curl',
      'axios request config',
      'nodejs axios converter',
      'axios typescript generator',
      'curl to axios online',
    ],
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'curl-to-httpx',
    name: 'cURL to httpx Converter',
    description:
      'Convert cURL commands to Python httpx client code with sync Client and async AsyncClient support',
    icon: '🐍',
    route: '/tools/curl-to-httpx',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to httpx',
      'python httpx from curl',
      'httpx generator',
      'async httpx python',
      'httpx client converter',
      'python async http from curl',
      'curl to python async',
      'httpx request builder',
    ],
    searchVolume: 8000,
    label: '',
  },
  {
    id: 'curl-to-go',
    name: 'cURL to Go Converter',
    description:
      'Convert cURL commands to Go code using net/http (stdlib) or Resty HTTP client',
    icon: '🐹',
    route: '/tools/curl-to-go',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to go',
      'curl to golang',
      'curl to net http',
      'curl to resty',
      'go http client generator',
      'golang api request',
      'go curl example',
      'curl converter golang',
      'go rest client generator',
      'curl to go online',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'curl-to-php',
    name: 'cURL to PHP Converter',
    description:
      'Convert cURL commands to PHP code using Guzzle, native cURL extension, or file_get_contents',
    icon: '🐘',
    route: '/tools/curl-to-php',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to php',
      'curl to guzzle',
      'curl to php curl',
      'curl to file_get_contents',
      'curl converter php',
      'php http client generator',
      'php api request',
      'php curl example',
      'composer guzzle',
      'curl php converter online',
    ],
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Converter',
    description:
      'Convert JSON to TypeScript interfaces with smart type inference, optional properties, and nested interface support',
    icon: '🔧',
    route: '/tools/json-to-typescript',
    categories: ['data', 'dev', 'generators'],
    keywords: [
      'json to typescript',
      'typescript interface generator',
      'json to interface',
      'type generator',
      'typescript types from json',
      'interface generator',
      'typescript converter',
      'json parser',
      'type inference',
      'typescript definitions',
      'api types',
      'type safety',
      'typescript interfaces',
      'json schema',
      'type generation',
      'developer tools',
      'code generator',
      'typescript typing',
      'json typing',
      'interface extractor',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier/Beautifier',
    description:
      'Minify, beautify and optimize CSS code with advanced compression options for production-ready stylesheets',
    icon: '🎨',
    route: '/tools/css-minifier',
    categories: ['formatters', 'dev', 'web'],
    keywords: [
      'css minifier',
      'css beautifier',
      'css formatter',
      'css compressor',
      'minimize css',
      'css optimization',
      'reduce css size',
      'css prettify',
      'css minify',
      'compress css',
      'css optimizer',
      'css cleaner',
      'production css',
      'css tools',
    ],
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'js-minifier',

    name: 'JavaScript Minifier/Beautifier',
    description:
      'Minify, beautify and optimize JavaScript code with ES6+ support, source maps, and advanced compression',
    icon: '⚡',
    route: '/tools/js-minifier',
    categories: ['formatters', 'dev'],
    keywords: [
      'javascript minifier',
      'js minifier',
      'javascript beautifier',
      'js formatter',
      'compress javascript',
      'minify js',
      'javascript optimizer',
      'js compression',
      'uglify js',
      'terser',
      'webpack optimizer',
      'production js',
      'bundle size',
      'tree shaking',
      'dead code elimination',
      'source maps',
      'obfuscation',
      'es6 minifier',
      'modern javascript',
    ],
    searchVolume: 22000,
    label: '',
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML to JSON Converter',
    description:
      'Convert between YAML and JSON formats with validation, type handling, and advanced formatting',
    icon: '🔄',
    route: '/tools/yaml-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'yaml',
      'json',
      'converter',
      'parser',
      'formatter',
      'yaml to json',
      'json to yaml',
      'data transformation',
      'config converter',
      'kubernetes',
      'docker',
      'docker compose',
      'ci cd',
      'github actions',
      'ansible',
      'swagger',
      'openapi',
      'multi document',
      'anchors',
      'aliases',
    ],
    searchVolume: 18000,
    label: '',
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    description:
      'Validate YAML syntax with detailed error messages, line numbers, and support for YAML 1.1 and 1.2 specifications',
    icon: '✅',
    route: '/tools/yaml-validator',
    categories: ['data', 'dev'],
    keywords: [
      'yaml',
      'validator',
      'syntax',
      'checker',
      'linter',
      'yaml lint',
      'yaml check',
      'yaml syntax',
      'validate yaml',
      'yaml error',
      'kubernetes',
      'docker compose',
      'config validation',
      'yaml 1.1',
      'yaml 1.2',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description:
      'Convert between Unix timestamps and human-readable dates with timezone support and batch processing',
    icon: '⏰',
    route: '/tools/unix-timestamp-converter',
    categories: ['data', 'dev'],
    keywords: [
      'unix',
      'timestamp',
      'epoch',
      'converter',
      'date',
      'time',
      'timezone',
      'utc',
      'milliseconds',
      'batch',
      'convert',
      'unix time',
      'epoch time',
      'datetime',
      'iso',
      'rfc',
      'posix',
    ],
    searchVolume: 20000,
    label: '',
  },
  {
    id: 'eml-to-html',
    name: 'EML to HTML Converter',
    description:
      'Convert EML email files to HTML with header extraction, attachment handling, and multi-view rendering',
    icon: '📧',
    route: '/tools/eml-to-html',
    categories: ['data', 'dev', 'formatters'],
    keywords: [
      'eml',
      'email',
      'html',
      'converter',
      'mime',
      'rfc822',
      'email parser',
      'eml viewer',
      'email to html',
      'email converter',
      'mime parser',
      'email headers',
      'email attachments',
      'email migration',
      'email forensics',
      'email template',
      'mailbox',
      'outlook',
      'thunderbird',
      'message',
      'rfc2822',
      'multipart',
      'base64',
      'quoted-printable',
    ],
    searchVolume: 2000,
    label: '',
  },
  {
    id: 'ai-prompt-token-counter',
    name: 'AI Prompt Token Counter',
    description:
      'Count tokens for AI prompts across GPT-4, Claude, Llama models with cost estimation and optimization',
    icon: '🤖',
    route: '/tools/ai-prompt-token-counter',
    categories: ['dev', 'generators', 'text'],
    keywords: [
      'token counter',
      'gpt token calculator',
      'claude tokens',
      'prompt tokens',
      'ai cost calculator',
      'token estimator',
      'openai tokens',
      'gpt-4 tokens',
      'llama tokens',
      'token count',
      'tokenizer',
      'api cost',
      'prompt optimization',
      'context window',
      'tiktoken',
      'ai pricing',
      'token visualization',
      'batch token count',
      'prompt engineering',
    ],
    searchVolume: 20000,
    label: '',
  },

  // PDF Tools
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description:
      'Convert PDF files to editable Word (DOCX) format with preserved formatting',
    icon: '📄',
    route: '/tools/pdf-to-word',
    categories: ['pdf'],
    keywords: [
      'pdf',
      'word',
      'docx',
      'convert',
      'converter',
      'pdf to word',
      'pdf to docx',
      'document',
      'edit',
      'format',
      'export',
      'transformation',
      'office',
      'microsoft word',
      'libre office',
      'editable',
    ],
    searchVolume: 1000000,
    label: '',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG Converter',
    description:
      'Convert PDF pages to JPG, PNG or WebP images directly in your browser',
    icon: '🖼️',
    route: '/tools/pdf-to-jpg',
    categories: ['pdf'],
    keywords: [
      'pdf to jpg',
      'pdf to jpeg',
      'pdf to image',
      'convert pdf to image',
      'pdf to jpeg online',
      'pdf page to image',
      'pdf to png',
      'extract images from pdf',
      'pdf to picture',
      'save pdf as image',
      'pdf page to jpg',
      'convert pdf pages to images',
    ],
    searchVolume: 120000,
    label: '',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description:
      'Combine multiple PDF files into one document — reorder, then merge, fast and private in your browser',
    icon: '📑',
    route: '/tools/merge-pdf',
    categories: ['pdf'],
    keywords: [
      'merge pdf',
      'combine pdf',
      'merge pdf online',
      'combine pdf files',
      'pdf merger',
      'join pdf',
      'pdf combiner',
      'merge pdf files free',
      'combine pdf into one',
      'append pdf',
      'concatenate pdf',
      'merge multiple pdf',
    ],
    searchVolume: 165000,
    label: '',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description:
      'Split a PDF into separate files by page — click between pages to set where to cut, fast and private',
    icon: '✂️',
    route: '/tools/split-pdf',
    categories: ['pdf'],
    keywords: [
      'split pdf',
      'split pdf by page',
      'pdf splitter',
      'extract pdf pages',
      'separate pdf pages',
      'split pdf online',
      'split pdf into multiple files',
      'cut pdf',
      'divide pdf',
      'extract pages from pdf',
      'split pdf free',
      'break pdf into pages',
    ],
    searchVolume: 110000,
    label: '',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description:
      'Convert multiple images (JPG, PNG, GIF, WebP) into a single PDF document with custom page sizes',
    icon: '🖼️',
    route: '/tools/image-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'image',
      'pdf',
      'convert',
      'jpg',
      'png',
      'gif',
      'webp',
      'image to pdf',
      'jpg to pdf',
      'png to pdf',
      'photo to pdf',
      'picture to pdf',
      'combine images',
      'merge images',
      'multiple images',
      'batch convert',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 300000,
    label: '',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description:
      'Convert JPG and JPEG images to PDF format with custom page sizes and layout options',
    icon: '🖼️',
    route: '/tools/jpg-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'jpg',
      'jpeg',
      'pdf',
      'convert',
      'jpg to pdf',
      'jpeg to pdf',
      'image to pdf',
      'photo to pdf',
      'picture to pdf',
      'jpg converter',
      'jpeg converter',
      'batch convert',
      'multiple jpg',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 1500000,
    label: '',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description:
      'Convert PNG images to PDF format with transparency support and custom page options',
    icon: '🖼️',
    route: '/tools/png-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'png',
      'pdf',
      'convert',
      'png to pdf',
      'image to pdf',
      'transparent',
      'transparency',
      'photo to pdf',
      'picture to pdf',
      'png converter',
      'batch convert',
      'multiple png',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 600000,
    label: '',
  },
  {
    id: 'gif-to-pdf',
    name: 'GIF to PDF',
    description:
      'Convert GIF images to PDF format preserving quality with custom page sizes',
    icon: '🖼️',
    route: '/tools/gif-to-pdf',
    categories: ['pdf', 'data'],
    keywords: [
      'gif',
      'pdf',
      'convert',
      'gif to pdf',
      'image to pdf',
      'animated gif',
      'photo to pdf',
      'picture to pdf',
      'gif converter',
      'batch convert',
      'multiple gif',
      'page size',
      'a4',
      'letter',
    ],
    searchVolume: 5000,
    label: '',
  },

  // Social Media Tools
  {
    id: 'whatsapp-link-generator',
    name: 'WhatsApp Link Generator',
    description:
      'Create WhatsApp click-to-chat links with pre-filled messages and QR codes',
    icon: '💬',
    route: '/tools/whatsapp-link-generator',
    categories: ['social', 'generators'],
    keywords: [
      'whatsapp',
      'link generator',
      'wa.me',
      'click to chat',
      'whatsapp link',
      'whatsapp api',
      'chat link',
      'whatsapp qr code',
      'business whatsapp',
      'whatsapp message',
      'wa link',
      'whatsapp shortcut',
      'contact link',
      'phone link',
      'messaging',
      'social media',
    ],
    searchVolume: 70000,
    label: '',
  },
  {
    id: 'utm-builder',
    name: 'UTM Link Builder',
    description:
      'Create trackable URLs with UTM parameters for marketing campaigns, analytics, and link tracking',
    icon: '🔗',
    route: '/tools/utm-builder',
    categories: ['social', 'generators', 'web'],
    keywords: [
      'utm',
      'link builder',
      'url builder',
      'utm parameters',
      'campaign tracking',
      'utm generator',
      'google analytics',
      'utm tags',
      'marketing links',
      'utm source',
      'utm medium',
      'utm campaign',
      'link tracking',
      'campaign url',
      'url tracking',
      'analytics',
      'marketing',
      'social media tracking',
      'qr code',
      'short link',
    ],
    searchVolume: 35000,
    label: '',
  },
  {
    id: 'youtube-timestamp-generator',
    name: 'YouTube Timestamp Generator',
    description:
      'Create YouTube timestamps and chapters with automatic link generation and time conversion',
    icon: '⏱️',
    route: '/tools/youtube-timestamp-generator',
    categories: ['social', 'generators'],
    keywords: [
      'youtube',
      'timestamp',
      'chapters',
      'youtube chapters',
      'video timestamp',
      'timestamp generator',
      'youtube time',
      'video chapters',
      'youtube link',
      'time converter',
      'hh:mm:ss',
      'video navigation',
      'youtube creator',
      'video description',
      'timestamp link',
    ],
    searchVolume: 6000,
    label: '',
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description:
      'Calculate Unix file permissions with visual grid, octal and symbolic notation converter',
    icon: '🔒',
    route: '/tools/chmod-calculator',
    categories: ['dev', 'generators'],
    keywords: [
      'chmod',
      'permissions',
      'linux',
      'unix',
      'file permissions',
      'chmod calculator',
      'chmod converter',
      'octal permissions',
      'symbolic permissions',
      'rwx',
      'read write execute',
      'owner group others',
      'chmod 755',
      'chmod 644',
      'chmod 777',
      'permission bits',
      'sysadmin',
      'server',
      'shell',
      'terminal',
    ],
    searchVolume: 11000,
    label: '',
  },
  {
    id: 'htaccess-generator',
    name: 'Htaccess Generator',
    description:
      'Generate .htaccess files for Apache with redirects, security rules, caching, and URL rewriting',
    icon: '⚙️',
    route: '/tools/htaccess-generator',
    categories: ['dev', 'generators', 'web'],
    keywords: [
      'htaccess',
      'htaccess generator',
      'apache',
      'redirect',
      '301 redirect',
      '302 redirect',
      'url rewrite',
      'mod_rewrite',
      'security headers',
      'caching',
      'gzip compression',
      'force https',
      'www redirect',
      'custom error pages',
      'directory protection',
      'password protect',
      'hotlink protection',
      'ip blocking',
      'file access',
      'mime types',
      'server configuration',
      'web server',
      'seo redirect',
    ],
    searchVolume: 8000,
    label: '',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description:
      'Generate placeholder text for designs, mockups, and layouts with customizable word, sentence, or paragraph count',
    icon: '📝',
    route: '/tools/lorem-ipsum-generator',
    categories: ['text', 'generators'],
    keywords: [
      'lorem ipsum',
      'lorem ipsum generator',
      'placeholder text',
      'dummy text',
      'filler text',
      'sample text',
      'text generator',
      'lipsum',
      'blind text',
      'greeking',
      'mockup text',
      'design placeholder',
      'paragraph generator',
      'random text',
      'latin text',
    ],
    searchVolume: 12500,
    label: '',
  },
  {
    id: 'string-case-converter',
    name: 'String Case Converter',
    description:
      'Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and more',
    icon: '🔤',
    route: '/tools/string-case-converter',
    categories: ['text', 'dev'],
    keywords: [
      'string case converter',
      'case converter',
      'camelCase',
      'PascalCase',
      'snake_case',
      'kebab-case',
      'CONSTANT_CASE',
      'SCREAMING_SNAKE_CASE',
      'Title Case',
      'Sentence case',
      'lowercase',
      'uppercase',
      'text transform',
      'variable naming',
      'code formatting',
      'naming convention',
      'string transformation',
      'text case',
      'convert case',
    ],
    searchVolume: 25000,
    label: '',
  },
  {
    id: 'word-counter',
    name: 'Word Counter & Reading Time',
    description:
      'Count words, characters, sentences, paragraphs and estimate reading time in real time',
    icon: '🔤',
    route: '/tools/word-counter',
    categories: ['text'],
    keywords: [
      'word counter',
      'character counter',
      'reading time calculator',
      'word count online',
      'words in text',
      'count words',
      'letter counter',
      'sentence counter',
      'paragraph counter',
      'text length',
      'character count',
      'words per minute',
      'text statistics',
      'word count tool',
    ],
    searchVolume: 90000,
    label: '',
  },
  {
    id: 'binary-to-text',
    name: 'Binary to Text Converter',
    description:
      'Convert binary numbers to text and vice versa with support for ASCII, UTF-8, and hex formats',
    icon: '🔢',
    route: '/tools/binary-to-text',
    categories: ['encoding', 'data'],
    keywords: [
      'binary to text',
      'text to binary',
      'binary converter',
      'binary decoder',
      'binary encoder',
      'ascii binary',
      'binary string',
      'binary code',
      'binary translation',
      '01 to text',
      'binary ascii converter',
      'binary to ascii',
      'ascii to binary',
      'hex to binary',
      'binary to hex',
      'utf-8 binary',
    ],
    searchVolume: 27000,
    label: '',
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description:
      'Convert numbers between binary, octal, decimal, hex and any base 2–36 with signed and bit-width options',
    icon: '🔢',
    route: '/tools/number-base-converter',
    categories: ['dev'],
    keywords: [
      'number base converter',
      'hex to decimal',
      'binary to decimal',
      'decimal to hex',
      'octal converter',
      'base conversion',
      'decimal to binary',
      'binary to hex',
      'radix converter',
      'base 2 to base 16',
      'twos complement converter',
      'hex converter',
      'binary converter',
      'base converter',
    ],
    searchVolume: 55000,
    label: '',
  },
  {
    id: 'js-object-to-json',
    name: 'JavaScript Object to JSON',
    description:
      'Convert JavaScript objects to valid JSON with circular reference detection, function handling, and BigInt support',
    icon: '🔄',
    route: '/tools/js-object-to-json',
    categories: ['data', 'dev'],
    keywords: [
      'javascript to json',
      'js object to json',
      'object to json',
      'json converter',
      'javascript object converter',
      'js to json online',
      'convert js to json',
      'json stringify',
      'object serialization',
      'circular reference',
      'bigint json',
      'function to json',
      'undefined json',
      'javascript parser',
      'json generator',
    ],
    searchVolume: 6000,
    label: '',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description:
      'Convert HTML to Markdown or Markdown to HTML with GFM table and code block support',
    icon: '🔄',
    route: '/tools/html-to-markdown',
    categories: ['text', 'formatters'],
    keywords: [
      'html to markdown',
      'markdown to html',
      'html to md',
      'html converter',
      'markdown converter',
      'html',
      'markdown',
      'convert',
      'md',
      'gfm',
      'github',
      'turndown',
      'wordpress to markdown',
      'notion markdown',
      'obsidian markdown',
      'copy html as markdown',
      'table',
      'code',
    ],
    searchVolume: 10000,
    label: '',
  },
  {
    id: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description:
      'Build Markdown tables visually or paste CSV/TSV. Configure column alignment, escape pipes, and export GFM-ready output',
    icon: '📐',
    route: '/tools/markdown-table-generator',
    categories: ['formatters', 'text'],
    keywords: [
      'markdown table',
      'markdown table generator',
      'markdown table creator',
      'csv to markdown',
      'tsv to markdown',
      'table to markdown',
      'gfm table',
      'github table',
      'markdown',
      'table',
      'generator',
    ],
    searchVolume: 30000,
    label: '',
  },
];

// Group tools by category
export const categories: Category[] = [
  {
    id: 'data',
    name: 'Data & Conversion',
    description:
      'Transform and format data between different formats like JSON, CSV, XML, and SQL.',
    icon: '📊',
    tools: getToolsByCategory('data'),
  },
  {
    id: 'encoding',
    name: 'Encoding & Security',
    description:
      'Encode, decode, hash, and secure your data with various encryption methods.',
    icon: '🔐',
    tools: getToolsByCategory('encoding'),
  },
  {
    id: 'base64',
    name: 'Base64',
    description:
      'Convert Base64 encoded data to PDF, images, and other file formats with instant download and preview.',
    icon: '🔤',
    tools: getToolsByCategory('base64'),
  },
  {
    id: 'text',
    name: 'Text & Format',
    description:
      'Process, compare, and format text content with powerful text manipulation tools.',
    icon: '📝',
    tools: getToolsByCategory('text'),
  },
  {
    id: 'generators',
    name: 'Generators',
    description:
      'Generate UUIDs, passwords, QR codes, and other useful content for development.',
    icon: '⚡',
    tools: getToolsByCategory('generators'),
  },
  {
    id: 'web',
    name: 'Web & Design',
    description:
      'Tools for web developers and designers including color pickers and image optimization.',
    icon: '🎨',
    tools: getToolsByCategory('web'),
  },
  {
    id: 'dev',
    name: 'Dev Utilities',
    description:
      'Development utilities for testing APIs, validating schemas, and debugging code.',
    icon: '🔧',
    tools: getToolsByCategory('dev'),
  },
  {
    id: 'formatters',
    name: 'Formatters',
    description:
      'Format and beautify code, SQL, JSON, XML and other structured data.',
    icon: '🪄',
    tools: getToolsByCategory('formatters'),
  },
  {
    id: 'social',
    name: 'Social Media',
    description:
      'Tools for social media content creation, including Instagram, WhatsApp, Twitter, and Facebook.',
    icon: '📱',
    tools: getToolsByCategory('social'),
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description:
      'Professional PDF tools for conversion, editing, merging, splitting and optimization.',
    icon: '📄',
    tools: getToolsByCategory('pdf'),
  },
];

// Helper functions
export function getPopularTools(): Tool[] {
  const pinned = tools.filter((tool) => tool.label === 'popular');
  const rest = tools
    .filter((tool) => tool.label !== 'popular')
    .sort((a, b) => b.searchVolume - a.searchVolume);

  return [...pinned, ...rest].map((tool) => ({
    ...tool,
    keywords: tool.keywords || [],
  }));
}

export function searchTools(query: string): Tool[] {
  const searchTerm = query.toLowerCase();
  return tools
    .filter(
      (tool) =>
        tool.label !== 'coming-soon' &&
        (tool.name.toLowerCase().includes(searchTerm) ||
          tool.description.toLowerCase().includes(searchTerm) ||
          tool.keywords.some((keyword) =>
            keyword.toLowerCase().includes(searchTerm)
          ))
    )
    .sort((a, b) => b.searchVolume - a.searchVolume);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools
    .filter((tool) => {
      return tool.categories.includes(categoryId);
    })
    .sort((a, b) => {
      // First sort by searchVolume (descending), then by name (ascending) for deterministic order
      if (b.searchVolume !== a.searchVolume) {
        return b.searchVolume - a.searchVolume;
      }
      return a.name.localeCompare(b.name);
    });
}

// O(1) lookup map for tools by ID
export const toolsMap = new Map<string, Tool>(tools.map((t) => [t.id, t]));

export function getToolById(id: string): Tool | undefined {
  return toolsMap.get(id);
}

export function getCategoryColorClass(categoryColor: string): string {
  const colorClasses = {
    data: 'border-blue-500 bg-blue-50 dark:bg-blue-950',
    encoding: 'border-green-500 bg-green-50 dark:bg-green-950',
    text: 'border-purple-500 bg-purple-50 dark:bg-purple-950',
    generators: 'border-orange-500 bg-orange-50 dark:bg-orange-950',
    web: 'border-pink-500 bg-pink-50 dark:bg-pink-950',
    dev: 'border-yellow-500 bg-yellow-50 dark:bg-yellow-950',
    formatters: 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950',
    social: 'border-rose-500 bg-rose-50 dark:bg-rose-950',
    pdf: 'border-red-500 bg-red-50 dark:bg-red-950',
  };
  return (
    colorClasses[categoryColor as keyof typeof colorClasses] ||
    'border-blue-500 bg-blue-50 dark:bg-blue-950'
  );
}

export function getCategoryByTool(tool: Tool): Category | undefined {
  return categories.find((category) =>
    category.tools.some((t) => t.id === tool.id)
  );
}

export function getAllTools(): Tool[] {
  return tools;
}
